### ISSUE TITLE
 [v0.5] Do not fail on missing labels

### ISSUE THREAD

**Issue by olblak** [rancher/fleet#1280] opened 2023-01-26 11:37 UTC
Original user issue https://github.com/rancher/fleet/issues/689

[How to test](https://github.com/rancher/fleet/issues/689#issuecomment-1387112245)

**Comment by kkaempf** [comment] 2023-02-03 15:11
[Fleet-0.5.2-rc3](https://github.com/rancher/fleet/releases/tag/v0.5.2-rc.3) is out.

**Comment by sowmyav27** [comment] 2023-02-07 19:16
@kkaempf can we tag the backport PR to this issue please?

**Comment by jameson-mcghee** [comment] 2023-02-07 20:23
During testing on Rancher version `v2.6.2` (_Fleet App_ version `100.0.1+up0.3.7`) as well as Rancher version `v2.7.0`, I able to reproduce the issue by following the Steps to Reproduce below.  However, during testing on Rancher version `v2.6-head` (Commit ID: e36364e) with _Fleet App_ version `100.2.2+up0.5.2-rc.3`, I was unable to reproduce the issue when following the Steps to Reproduce. I was able to see the message mentioned as part of the fix in the logs:
`time="2023-02-07T20:19:42Z" level=info msg="Cluster label 'global.fleet.clusterLabels.LABELNAME' for key 'variableName' is missing from some clusters, setting value to empty string for these clusters."`

**Steps to Reproduce:**
1. Fork the [rancher/fleet-examples](https://github.com/rancher/fleet-examples) repo
2. Created a [branch on that fork](https://github.com/jameson-mcghee/fleet-examples/tree/test689)
3. Pull it down locally, modify the `multi-cluster/helm/fleet.yaml` file, and push changes to the remote branch
   - This is the `fleet.yaml` file that was able to reproduce the issue:
     - [fleet.yaml](https://github.com/jameson-mcghee/fleet-examples/blob/test689/multi-cluster/helm/fleet.yaml)
4. Open the `fleet-controller` logs from the `local` branch
5. Provision a downstream RKE2 cluster
6. Create a _Git Repo_ in _Continuous Delivery_ pointing to the forked repo/branch with the _Path_ `multi-cluster/helm`
7. Observe the `fleet-controller` logs

**`v2.6.2` Fleet Controller Logs:**
[fleet-controller-66cc4c6b5b-22282_fleet-controller.log](https://github.com/rancher/fleet/files/10467770/fleet-controller-66cc4c6b5b-22282_fleet-controller.log)

**`v2.6-head` (Commit ID: e36364e) Fleet Controller Logs:**
[fleet-controller-74fb89695b-hldfv_fleet-controller.log](https://github.com/rancher/fleet/files/10679099/fleet-controller-74fb89695b-hldfv_fleet-controller.log)



**Additional Information:**
With the above testing completed, once the correct PR is associated with this ticket, it should be able to be closed.
cc @kkaempf @sowmyav27

**Comment by kkaempf** [comment] 2023-02-08 10:00
> @kkaempf can we tag the backport PR to this issue please?

https://github.com/rancher/fleet/pull/1114

**Comment by jameson-mcghee** [comment] 2023-02-08 22:10
Based on the previous validation testing that was performed as well as the addition of the [associated PR](https://github.com/rancher/fleet/pull/1114) linked on the ticket, I am closing this ticket as Done.

**Closed by jameson-mcghee** 2023-02-08 22:10 UTC
Labels: area/fleet, [zube]: Blocked, team/fleet, kind/backport
