### ISSUE TITLE
Clean up left-over registration resources

### ISSUE THREAD

**Issue by manno** [rancher/fleet#1615] opened 2023-06-23 14:00 UTC
We added clean up for the `request-` service accounts in  https://github.com/rancher/fleet/pull/1310/files 
There were several annotations, which we did not convert to labels. The clean up code seems to ignore resources.

Yet, with Fleet 0.7 we see left over `request-` service account tokens.

**Comment by sbulage** [comment] 2023-06-23 14:25
When upgraded rancher from 2.7.3 --> 2.7.4 --> 2.7.5-rc5 I see spike in increase of `request-` service accounts/tokens are remaining.

![Selection_038](https://github.com/rancher/fleet/assets/12134754/0935e704-409e-43e4-b540-3ce6845751e4)

**Comment by manno** [comment] 2023-07-17 16:26
It's been reported that this is not new behavior.

The "ClusterRegistration" CR is created by the fleet-agent. While it is an owner of other resources, like the `request-` rolebinding, it has no owner. From reading the code, it seems it is [only deleted when the `Cluster` resource is deleted](https://github.com/rancher/fleet/blob/fix-resource-status-timestamp/internal/cmd/controller/controllers/cluster/controller.go#L118-L131). 

Related issues:

* https://github.com/rancher/fleet/issues/1605 (same problem)


Why is the registration process failing, why does the agent create multiple cluster registrations, instead of updating a single registration request? Since they use `GenerateName` this seems to be by design.

**Comment by manno** [comment] 2023-07-21 13:19
closing as duplicate of https://github.com/rancher/fleet/issues/1656

**Comment by manno** [comment] 2023-07-21 14:40
re-opening since #1656 is a backport issue

**Comment by kkaempf** [comment] 2023-07-24 10:12
closing as duplicate of #1651

**Closed by kkaempf** 2023-07-24 10:12 UTC
Labels: kind/enhancement, area/performance, status/waiting-for-fleet-rc-and-chart, area/fleet, team/fleet, kind/duplicate
