### ISSUE TITLE
Unabel to Utilize Auth Based Helm Packages

### ISSUE THREAD

**Issue by thecrazyrussian** [rancher/fleet#307] opened 2021-03-11 18:03 UTC
We have helm packages that are stored in our fleet repository as .tar.gz files, the repository is behind auth but when we include local helm chart paths, they are not getting processed.

Recreate:
package our example guestbook fleet sample as guestbook.tar.gz, upload it to the repository, and reference it locally in fleet.yaml. The package is not read or parsed for resources but the bundle shows it is installed successfully without installing contents of the tgz file.

rancher 2.5.6

gz#14979

**Comment by oxr463** [comment] 2021-03-24 14:14
Possible duplicate of https://github.com/rancher/fleet/issues/120

**Comment by thecrazyrussian** [comment] 2021-03-25 18:34
It is a duplicate of #120 @oxr463 .

**Closed** 2021-03-25 18:34 UTC
Labels: bug, internal
