### ISSUE TITLE
Ensure GitJob webhooks consider branches and/or revisions

### ISSUE THREAD

**Issue by nickgerace** [rancher/fleet#588] opened 2021-11-01 15:24 UTC
Currently, GitJob webhooks only match on URL. GitJob webhooks should take the branch into consideration and not just default to the latest commit by time.

**Comment by nickgerace** [comment] 2021-11-10 17:06
Available on Rancher v2.6-head in Fleet v0.3.8-rc1

**Comment by StrongMonkey** [comment] 2021-11-17 21:35
@davidnuzik 
To order to configure webhook, you can follow the docs at https://fleet.rancher.io/webhook/. TLDR, you will need to configure an ingress to point to gitjob service in `cattle-fleet-system`(the doc mention `fleet-system` which is out of date for 2.6 and latest fleet) and use that as webhook callback url.

To reproduce this:
1. Go to continous delivery and Create two gitRepos with two different branches, like `prod` and `dev`. You can use your own fork of https://github.com/rancher/fleet-examples so you can configure webhook.
2. Follow docs to add webhook to point to your ingress that is pre-configured.
3. Push any changes to your branches. You should see both gitRepos get updated immediately(check gitRepo.Status.Commit) when you push changes from your branches. Also if you haven't set the pollInterval of your gitRepo, it will be configured to 1 hour if webhook is enabled.

The bug is that if you only update `prod` branch, both gitrepo from `prod` and `dev` will get updated with the commit you pushed. This is unintended behavior and should be fixed in v0.3.8-rc1.

**Comment by davidnuzik** [comment] 2021-11-23 23:59
Putting this on pause until https://github.com/rancher/rancher/issues/35618 is fixed

**Comment by davidnuzik** [comment] 2021-12-14 03:03
**My checks PASSED**
Started with a fork of fleet-examples for my git repos with commit id `1dfd887` in each `prod` and `dev` branch I created. Pushed an update to the `prod` branch resulting in commit id `adbc161` and in the reproduction environment it updated BOTH branches (which is not expected and is the bug) and in the validation environment it only updated the `prod` branch (this is expected and is a result of the fix).
 
**Reproduction Environment:**

Rancher version: v2.6.2
Rancher cluster type: HA Install
 
Downstream cluster type: RKE2
Downstream K8s version: v1.21.6+rke2r1
 
**Reproduction steps:**

1. Fork https://github.com/rancher/fleet-examples and create two branches like `prod` and `dev`.
2. Create two gitRepos in the UI under Continuous Delivery -> Git Repos page. The first one for the `prod` branch, the second one for the `dev` branch.
3. Follow the docs [here](https://fleet.rancher.io/webhook/) to create an Ingress pointing to the gitjob service and to create a webhook in GitHub. I leveraged sslip to point to one of my three rancher nodes (and to the gitjob service). Test and confirm the webhook works correctly. This works, (200 OK).
4. Now, Push any change to the `prod` branch. Confirmed that BOTH the `dev` branch and the `prod` branch get updated. This is not expected and is the bug (only the prod branch should get updated).
 
-----
 
**Validation Environment:**
Rancher version: v2.6.3-rc4
Rancher cluster type: HA Install
 
Downstream cluster type: RKE2
Downstream K8s version: v1.21.7+rke2r2
 
**Validation steps:**
1. Fork https://github.com/rancher/fleet-examples and create two branches like `prod` and `dev`.
2. Create two gitRepos in the UI under Continuous Delivery -> Git Repos page. The first one for the `prod` branch, the second one for the `dev` branch.
3. Follow the docs [here](https://fleet.rancher.io/webhook/) to create an Ingress pointing to the gitjob service and to create a webhook in GitHub. I leveraged sslip to point to one of my three rancher nodes (and to the gitjob service). Test and confirm the webhook works correctly. This works, (200 OK).
4. Now, Push any change to the `prod` branch. Confirmed that the `dev` branch does NOT also get updated with that commit (this is confirmation of the fix and resolves the issue).
 
**Additional Info:**
Here is a screenshot showing on top the reproduction environment, there we see both branches are updated to the new commit (ending in 161) even though I only pushed a change to the `prod` branch. (successful reproduction) and below we see v2.6.3-rc4 which contains the fix - there the new commit is only seen in prod, as expected (successful validation).
Please ignore the fact that in the validation environment the "prod-branch" gitrepo is Not Ready. This is not relevant to the validation. This is because one of the required clusters is not set up with a cloud provider due to an unrelated bug, but it has no effect in any way/shape/form to proper validation of the issue.
![image](https://user-images.githubusercontent.com/45179589/145925019-2df9e0ac-c285-4c53-bd96-6f9312339c32.png)

**Closed by davidnuzik** 2021-12-14 03:03 UTC
Labels: internal, [zube]: QA Working, team/area3
