### ISSUE TITLE
[SURE-7437] GitRepo Stalled: true condition not cleared after transient connectivity issue to api.github.com

### ISSUE THREAD

**Issue by kkaempf** [rancher/fleet#2621] opened 2024-07-08 16:38 UTC
### Issue description:
In an environment with many GitRepos/Bundles, the Stalled: true condition is not cleared after a transient connectivity issue from the gitjob Pod in the Rancher local cluster to the api.github.com endpoint (in the case of GitHub GitRepos) although fleet syncing and reconciliation of the GitRepos continues to work as expected.

The issue is only reproducible in an environment of some scale: I recreated this error state with 30 GitRepos/150 Bundles similar to customer environment, but could not reproduce with a single GitRepo. As a result, I hypothesise if this is somehow related to the "rate limited gitjobs" messages observed within the fleet-controller logs.

### Business impact:
Confusing to the user, appears as though GitRepos are in an error state when they are not

**Comment by 0xavi0** [comment] 2024-07-30 08:28
So far I couldn't reproduce this with the latest `fleet` (0.10 main).
Note that quite some things changed from previous versions around the `gitjob` controller and also we recently merged https://github.com/rancher/fleet/pull/2681 which fixed some issues with conditions.

I would wait to get the above PR ready in an RC, retest and see if somebody is able to recreate it.

**Comment by kkaempf** [comment] 2024-08-08 09:02
I closed the Jira issue.

@sbulage - try to reproduce the issue in 2.9.1 (if you find time)

**Comment by sbulage** [comment] 2024-08-08 09:25
> I closed the Jira issue.
> 
> [@sbulage](https://github.com/sbulage) - try to reproduce the issue in 2.9.1 (if you find time)

I will give a try and update here. Thanks 😄

**Comment by sbulage** [comment] 2024-08-09 12:44
I was not able to reproduce this issue on 2.9.1 by using public and private GitHub repository. In both the cases I have tried to wait or played with my internet connection etc. for more than ~18 hours. Not able to reproduce it on Rancher: 2.9.1 with Fleet version: 0.10.1-rc.1. Closing issue.

**Closed by sbulage** 2024-08-09 12:44 UTC
Labels: kind/bug, JIRA, area/gitjob
