### ISSUE TITLE
[SURE-5453] Fleet-controller and Rancher fight over labels and annotations on cluster.fleet.cattle.io/local resource

### ISSUE THREAD

**Issue by skaven81** [rancher/fleet#1365] opened 2023-03-02 18:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

~At seemingly random times, around 2-3 times per day~ Every 10 hours, the fleet-controller issues a PATCH against the `clusters.fleet.cattle.io/local` resource in the `fleet-local` namespace (the Fleet cluster resource representing the Rancher management server cluster where the fleet-controller is itself running).  The PATCH looks like this:

```
   requestObject: {
     metadata: {
       annotations: {
         objectset.rio.cattle.io/applied: <redacted for brevity>
         objectset.rio.cattle.io/id: fleet-bootstrap
         objectset.rio.cattle.io/owner-gvk: null
         objectset.rio.cattle.io/owner-name: null
         objectset.rio.cattle.io/owner-namespace: null
       }
       labels: {
         management.cattle.io/cluster-display-name: null
         management.cattle.io/cluster-name: null
         name: local
         objectset.rio.cattle.io/hash: 67f475f626e5473772f6084a291170a9de5942d1
         provider.cattle.io: null
       }
     }
   }
```

Observe that several rather important labels have their values set to `null`.  The `management.cattle.io` ones are automatically by Rancher (not sure which is supposed to be the "owner" of those labels).  We depend on these labels in our GitRepo clusterSelector statements, and when they vanish, most of our BundleDeployments mapped to the `local` cluster, get marked for deletion.

Within a few seconds, Rancher comes to the rescue and issues its own PATCH to correct the issue:

```
   requestObject: {
     metadata: {
       annotations: {
         objectset.rio.cattle.io/applied: <redacted for brevity>
         objectset.rio.cattle.io/id: fleet-cluster
         objectset.rio.cattle.io/owner-gvk: provisioning.cattle.io/v1, Kind=Cluster
         objectset.rio.cattle.io/owner-name: local
         objectset.rio.cattle.io/owner-namespace: fleet-local
       }
       labels: {
         management.cattle.io/cluster-display-name: local
         management.cattle.io/cluster-name: local
         name: null
         objectset.rio.cattle.io/hash: f2a8a9999a85e11ff83654e61cec3a781479fbf7
         provider.cattle.io: rke
       }
     }
   }
```

It seems clear that Fleet-controller and Rancher are fighting over who actually owns this resource and the annotations and labels it contains.  Each time they "fight", Rancher ends up winning, but fleet-controller keeps coming back every few hours to try again.  And each time this "fight" happens, GitRepos that use any of these labels to target a deployment into the `local` cluster, have the deployment removed and then immediately reinstalled.

### Expected Behavior

fleet-controller should not modify annotations or labels that it does not own.

Rancher should not modify annotations or labels that it does not own.

Fleet and Rancher should have _mutually exclusive_ annotations/labels that they own.

### Steps To Reproduce

This problem first appeared when we upgraded from Rancher 2.5 to Rancher 2.6.  We are currently on Rancher 2.6.9 and the problem persists.

We made no specific change to the environment to trigger this behavior.  No new GitRepos or Bundle configuration changes -- it just started at the time we upgraded Rancher.

### Environment

```markdown
- Architecture: amd64
- Fleet Version: 0.4.0 (Rancher 2.6.9)
- Cluster:
  - Provider: RKE
  - Options: 3 VMware nodes, no special customizations
  - Kubernetes Version: 1.21.10
```

**Comment by skaven81** [comment] 2023-03-02 19:38
One interesting observation is that the `fleet-stage: dev` label is the only _custom_ label that gets added/removed during the "fight" between fleet-controller and Rancher.  And that's also the only extra/custom label present on the `clusters.management.cattle.io/local` resource.  

I believe Rancher 2.6 added a one-way sync of labels from the `clusters.management.cattle.io` resources to the `clusters.fleet.cattle.io` resources, as a way of making the Fleet UI more intuitive, as labels added to clusters in the cluster manager would find their way to the Fleet cluster resources and behavior would work as expected.

We have been using Fleet since before this sync behavior existed, so we have always just put all our labels on the `clusters.fleet.cattle.io` resources directly.  But it seems this wone `fleet-stage: dev` label got added by an admin that wasn't aware there were separate cluster resources for Fleet.  So I now wonder if it's that one-way sync process that is causing this behavior.  I've removed the `fleet-stage: dev` label from the `clusters.management.cattle.io/local` resource and will wait and see if the flapping stops.

**Comment by skaven81** [comment] 2023-03-02 19:38
Another data point is that the label mangling happens precisely on a 10-hour cycle, which I believe is a hard-coded fleet-controller sync loop timer.

**Comment by skaven81** [comment] 2023-03-03 18:22
Further tests have shown that if we update our GitRepos to not require these labels (for targeting the `local` cluster) then our immediate problem goes away (the BundleDeployment doesn't keep getting removed and re-added every 10 hours).  But we do still see the fighting PATCH events every 10 hours between fleet-controller and rancher.

For example, we changed this rule:
```
targets:
- clusterSelector:
    management.cattle.io/cluster-name: local
```
to this:
```
targets:
- clusterName: local
```
as a workaround.  But this is obviously not a permanent solution.  As it also means we have to do awkward stuff like converting this:
```
  targets:
  - clusterSelector:
      matchExpressions:
      - key: management.cattle.io/cluster-display-name
        operator: In
        values:
        - sddemo
        - eks-zt-gw-dev
        - sdid
        - sddev
        - local
```
to this:
```
  targets:
  - clusterName: local
  - clusterSelector:
      matchExpressions:
      - key: management.cattle.io/cluster-display-name
        operator: In
        values:
        - sddemo
        - eks-zt-gw-dev
        - sdid
        - sddev
```
which is rather ridiculous.

**Comment by atsai1220** [comment] 2023-03-29 05:05
We are experiencing this still with 2.7.1 and also with fleet 0.5.3. It seems past issues were closed.
- https://github.com/rancher/fleet/issues/1163
- https://github.com/rancher/fleet/pull/1155
- https://github.com/rancher/fleet/issues/1079

The fix seems to be here but perhaps unreleased: https://github.com/rancher/rancher/pull/40176

**Comment by manno** [comment] 2023-03-29 16:58
https://github.com/rancher/rancher/pull/40176 was meant to fix this at least for the "name=local" label. The fix should be in 2.7.2.

However, if I understand correctly the  "hard-coded fleet-controller sync loop timer" will overwrite the labels and annotations from the Rancher with fleet's own cluster resource? That would indeed be a problem when using custom labels in a bundle selector.

> Fleet only changes the local cluster via bootstrap.go. This happens for controller restarts and changes to the fleet-controller config map.

Also, I'm not sure where the sync loop timer could be hard coded (wrangler?), in any case that might trigger bootstrap.

I was [under the impression that fleet uses a three way merge](https://github.com/rancher/fleet/pull/1155#issuecomment-1357492055) and retains custom labels. 

Since that relies on the [applied hash](https://github.com/rancher/wrangler/blob/master/pkg/apply/desiredset_compare.go#L427), it should keep labels from another apply (like in Rancher), but it might remove labels that were put manually.

**Comment by manno** [comment] 2023-03-30 09:23
The sync timer is [hard coded in lasso to 600 minutes](https://github.com/rancher/lasso/blob/6ea88ca2fbcc8cadc89c30421b0766e9993c4b7a/pkg/cache/cache.go#L20).

Fleet 0.6.x (to be released with Rancher 2.7.2) disables [resyncs](https://github.com/rancher/fleet/pull/1041) for performance. That should help a bit.

I would assume a resync is similar to a controller restart, which I tested. I didn't see label changes in my tests. There is a difference between manually created labels and labels created from Rancher's `apply`, though.
Maybe fleet does need to upsert the cluster resource.

**Comment by manno** [comment] 2023-04-17 12:09
Wrangler's apply tracks ownership with a set of custom annotations (`objectset.rio.cattle.io/id`, ...). A hash is calculated over these fields to be able to find resources again. `Apply` then [uses that hash to find the existing resource](https://github.com/rancher/wrangler/blob/840afd155e327c1317eca363d38b287347801471/pkg/apply/desiredset_apply.go#L111-L118) and construct a  diff patch.

Since the fleet controller and the rancher controller use different owners for the same local cluster resource the labels are overwritten.

A possible solution could be to [disable bootstrapping in the fleet controller](https://github.com/rancher/fleet/pull/1207). The Rancher controllers already bootstrap and manage the local cluster.

**Comment by kkaempf** [comment] 2023-05-24 13:10
QA template is in https://github.com/rancher/rancher/pull/41193

**Comment by kkaempf** [comment] 2023-06-13 07:40
@sbulage @manno - are we good to close this issue as done ?

**Comment by sbulage** [comment] 2023-06-13 08:28
@kkaempf Not able to reproduce on latest fleet version which has fix (https://github.com/rancher/rancher/pull/41193) included.

**Closed** 2023-06-14 10:36 UTC
Labels: [zube]: Done, kind/bug, area/fleet, team/fleet
