### ISSUE TITLE
Panic when fleet agent trying to locate fleet-agent secret

### ISSUE THREAD

**Issue by aDisplayName** [rancher/fleet#2255] opened 2024-03-21 17:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Upon the onboarding an imported downstream cluster (after cattle-cluster-agent started), the fleet-agent failed to start with following error messages:

```
 leaderelection.go:248] attempting to acquire leader lease cattle-fleet-system/fleet-agent-lock...
 leaderelection.go:258] successfully acquired lease cattle-fleet-system/fleet-agent-lock
time="2024-03-21T16:02:37Z" level=warning msg="Cannot find fleet-agent secret, running registration"
panic: assignment to entry in nil map

goroutine 16 [running]:
github.com/rancher/fleet/internal/cmd/agent/register.createAgentSecret({0x2b22940, 0xc00083a460}, {0x0, 0x0}, {0x2b2f1d0, 0xc00059a860}, 0xc00030e000)
	/go/src/github.com/rancher/fleet/internal/cmd/agent/register/register.go:174 +0x3dc
github.com/rancher/fleet/internal/cmd/agent/register.runRegistration({0x2b22940, 0xc00083a460}, {0x2b2f1d0?, 0xc00059a860?}, {0xc00005800a, 0x13}, {0x0, 0x0})
	/go/src/github.com/rancher/fleet/internal/cmd/agent/register/register.go:118 +0x1af
github.com/rancher/fleet/internal/cmd/agent/register.tryRegister({0x2b22940, 0xc00083a460}, {0xc00005800a, 0x13}, {0x0, 0x0}, 0x0?)
	/go/src/github.com/rancher/fleet/internal/cmd/agent/register/register.go:81 +0x325
github.com/rancher/fleet/internal/cmd/agent/register.Register({0x2b22940, 0xc00083a460}, {0xc00005800a, 0x13}, {0x0, 0x0}, 0x0?)
	/go/src/github.com/rancher/fleet/internal/cmd/agent/register/register.go:53 +0x97
github.com/rancher/fleet/internal/cmd/agent.start.func1({0x2b22940, 0xc00083a460})
	/go/src/github.com/rancher/fleet/internal/cmd/agent/start.go:58 +0x9e
created by github.com/rancher/wrangler/pkg/leader.run.func1
	/go/pkg/mod/github.com/rancher/wrangler@v1.1.1/pkg/leader/leader.go:58 +0x98
```

### Expected Behavior

Fleet-agent successful loaded and running with following logs:

```
I0321 17:31:05.340401       1 leaderelection.go:248] attempting to acquire leader lease cattle-fleet-system/fleet-agent-lock...
I0321 17:31:53.142218       1 leaderelection.go:258] successfully acquired lease cattle-fleet-system/fleet-agent-lock
time="2024-03-21T17:31:53Z" level=warning msg="Cannot find fleet-agent secret, running registration"
time="2024-03-21T17:31:54Z" level=info msg="Creating clusterregistration with id 'xxxxxxxxxxxxxxx' for new token"
time="2024-03-21T17:31:56Z" level=info msg="Waiting for secret 'cattle-fleet-clusters-system/c-xxxxxxxxxxxxxxx' on management cluster for request 'fleet-default/request-w5trt': secrets \"c-xxxxxxxxxxxxxxx\" not found"
time="2024-03-21T17:32:01Z" level=info msg="Starting /v1, Kind=Node controller"
time="2024-03-21T17:32:01Z" level=info msg="Starting /v1, Kind=ConfigMap controller"
time="2024-03-21T17:32:01Z" level=info msg="Starting /v1, Kind=Secret controller"
time="2024-03-21T17:32:01Z" level=info msg="Starting /v1, Kind=ServiceAccount controller"
E0321 17:32:02.581898       1 memcache.go:206] couldn't get resource list for management.cattle.io/v3: 
```

### Steps To Reproduce

Not easy to reproduce. In our fleet, it happens less than 10% during our production usage.

### Environment

```markdown
- Architecture: amd64
- Fleet Version: 0.8.1
- Cluster:
  - Provider: k3s hosted under Ubuntu 22.04
  - Options: single node
  - Kubernetes Version: v1.21.14+k3s1

Rancher: 2.7.10
```

### Anything else?

We found the workaround: In Rancher portal, go to `Continuous Delivery` &rarr; `Clusters`, find the cluster entry, and perform `Force Update`, will normally fix the problem

**Comment by manno** [comment] 2024-03-22 12:19
The panic happens in https://github.com/rancher/fleet/blob/v0.8.1/internal/cmd/agent/register/register.go#L173-L174

This is a duplicate of https://github.com/rancher/fleet/issues/2062 and should be fixed in [0.8.2](https://github.com/rancher/fleet/releases/tag/v0.8.2) 
> Initialise cluster registration labels map if empty by @weyfonk in https://github.com/rancher/fleet/pull/2063

Please reopen if the issue persists.

**Closed by manno** 2024-03-22 12:19 UTC
Labels: [zube]: To Triage, kind/bug, area/fleet, team/fleet
