### ISSUE TITLE
meta.helm.sh/release-name mismatch causes reinstall every few minutes - even for non-Helm resources

### ISSUE THREAD

**Issue by paulchoi** [rancher/fleet#448] opened 2021-07-01 17:59 UTC
I ran into an issue where fleet-agent kept reinstalling some daemonsets. I also ran into an issue with a deployment as well.
Seems to be a mismatch between the Helm release name that Fleet expects, vs the annotation value for `meta.helm.sh/release-name`.

It seems like even for a collection of raw YAMLs (not a Helm chart), a Helm release name is generated.

Saw in fleet-agent:
```
time="2021-06-29T21:19:53Z" level=info msg="Deleting unknown bundle ID nv-gpu-feature-discovery-nvidia-gpu-feature-discovery, release nvidia/nv-gpu-feature-discovery-nvidia-gpu-feature-dis-cc187, expecting release nvidia/nv-gpu-feature-discovery-nvidia-gpu-feature-discovery"
```

**workaround**: The workaround for us was to set an explicit `helm.releaseName` so the name isn't truncated. I believe it may have to do with the 63-character limit for Helm release name.

Can we document this behavior somewhere? I don't know if there's a good guardrail feature that we can associate with this.

**Comment by atsai1220** [comment] 2021-12-16 18:45
After updating `helm.releaseName` and making sure the deployed resources have matching `meta.helm.sh/release-name`, our objects are still getting removed seemingly randomly from Fleet.

The bundle would describe objects as `missing`. 

Our `fleet.yaml`:
```yaml
defaultNamespace: kube-system
helm:
  takeOwnership: true
  releaseName: best-name
targetCustomizations:
# BEGIN usw1-dockyard-local
- name: foo
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: cluster-one
  yaml:
    overlays:
    - cluster-one
```

File directory:
```
fleet.yaml
overlays/cluster-one/*.yaml
overlays/cluster-two/*.yaml
overlays/cluster-three/*yaml
```

**Comment by frouzbeh** [comment] 2022-02-23 20:32
Hi, I'm seeing the same problem. I don't think the problem is about the 63 characters release name, because ours name is already less than 63 characters. Any reason why it's happening?

**Comment by aiyengar2** [comment] 2022-06-16 23:21
@paulchoi apologies for the late response but thank you for filing this issue!

Did you test this on a Fleet version >0.3.5 when you filed the issue? I believe this issue was fixed with https://github.com/rancher/fleet/commit/e4332617887613decf003868592e8de24b66403b, this would ensure that the workaround for making the release name <63 characters should not be required since the generated bundle names are always truncated to 53 characters if the release name isn't provided.

Moving this over to test.

---

re: " fleet-agent kept reinstalling some daemonsets" and @atsai1220 "our objects are still getting removed seemingly randomly from Fleet", I wasn't able to reproduce those issues but I suspect the root issue you are running into is related to https://github.com/rancher/fleet/issues/676; currently, Fleet does not clean up old Bundles on refreshing a GitRepo, so if you renamed your bundle's path from one place to another the old Bundle and the new Bundle may both be generating BundleDeployments that fleet-agent is trying to simultaneously deploy. Through this, I was able to reproduce an `ErrApplied` status on the latest fleet as shown below:

![Screen Shot 2022-06-16 at 4 17 07 PM](https://user-images.githubusercontent.com/13127443/174193526-c54bd0e5-b0cc-4d83-b966-2cc459f5a291.png)

In this case, the error is fairly straightforward since both releases are still trying to track the same underlying Helm managed resource, so Helm emits an error. However, depending on what you are seeking to deploy via your Helm chart (i.e. if your Helm charts deploy a Job that modifies resources via kubectl outside of Helm like with rancher-monitoring-crd deployed via Fleet), this type of duplicate Bundle scenario could result in other conditions like the ones noted above in the comments.

If this is still an issue you are encountering, could you open up a separate ticket for that issue with more steps to reproduce so we can identify what might be happening?

**Comment by aiyengar2** [comment] 2022-06-16 23:55
> Did you test this on a Fleet version >0.3.5 when you filed the issue? I believe this issue was fixed with https://github.com/rancher/fleet/commit/e4332617887613decf003868592e8de24b66403b, this would ensure that the workaround for making the release name <63 characters should not be required since the generated bundle names are always truncated to 53 characters if the release name isn't provided.

I need to correct this; the real fix for this issue appeared only in Fleet 0.3.8 as part of fixing https://github.com/rancher/fleet/commit/74c6f927265998d82809a33ae69be3128cd1010b, where we limit the generated name for a bundle via the `fleet-apply` command automatically to be a maximum of 63 characters.

https://github.com/rancher/fleet/issues/432 is a duplicate of this issue and as indicated by the milestone this should have been fixed in Rancher 2.6.3.

**Comment by izaac** [comment] 2022-07-06 19:13
Rancher version: `v2.6.6`
Fleet version : `v0.3.9`

I was able to reproduce the issue by renaming a folder in the git repository that's configured as GitRepo as mentioned in [this comment](https://github.com/rancher/fleet/issues/448#issuecomment-1158257305).

The bundle that's kept with the old name is still there and stuck in modifying state due to #676

**Closed** 2022-07-18 18:03 UTC
Labels: [zube]: To Test, area/fleet

**Comment by atsai1220** [comment] 2022-07-21 21:35
Thank you! Will Fleet self-resolve the existing bundles after the upgrade?
