### ISSUE TITLE
Feature Request: Cluster specific registry that the agent image is pulled from

### ISSUE THREAD

**Issue by mattfarina** [rancher/fleet#948] opened 2022-08-31 19:06 UTC
### Is your feature request related to a problem?

Yes. Rancher has the ability to specify cluster specific registries. These are useful in a variety of ways. When fleet is used with Rancher the cluster specific registry is not passed on for fleet to use. This is a problem when Rancher relies on fleet and it doesn't work with the cluster specific registry.

### Solution you'd like

1. To have the fleet Cluster CRD extended to add a registry
2. When fleet installs an agent in that cluster the registry on the Cluster CR is used for the image to install

### Alternatives you've considered

N/A

### Anything else?

This is a sub-task of the epic at [#712](https://github.com/rancher/fleet/issues/712)

This should not be closed until Rancher is updated to use the change. The change, I believe, needs to be made at [here](https://github.com/rancher/rancher/blob/3e5fb4a537731df7ed96cc9ddae6a3902a57c8b1/pkg/controllers/provisioningv2/fleetcluster/fleetcluster.go#L118-L129). I think you can use the function [`GetPrivateRepoURLFromCluster`](https://github.com/rancher/rancher/blob/3e5fb4a537731df7ed96cc9ddae6a3902a57c8b1/pkg/provisioningv2/image/resolve.go#L34) to get the private repo from the cluster instance.

**Comment by mattfarina** [comment] 2022-09-28 19:18
This is half implemented. Fleet now supports cluster specific registries via the [privateRepoUrl](https://github.com/rancher/fleet/blob/d33b1f3cf3e827ec808b5eedd29e5ca6a4d70380/charts/fleet-crd/templates/crds.yaml#L1782) (also [here](https://github.com/rancher/fleet/blob/d33b1f3cf3e827ec808b5eedd29e5ca6a4d70380/pkg/apis/fleet.cattle.io/v1alpha1/target.go#L70)) property.

The [PR for Rancher to leverage this](https://github.com/rancher/rancher/pull/38950) did not make it in for 2.7.0 so we are targeting 2.7.1.

**Comment by mattfarina** [comment] 2022-10-03 18:46
Rancher Manager now works with credentials for private repos. We need to support them. This was fixed in https://github.com/rancher/rancher/pull/39059. It was a bug because the credentials were input but not being used properly.

To get the name of the secret we should be able to use the function `GetPrivateRepoSecretFromCluster`. It's in the same package as `GetPrivateRepoURLFromCluster`. It's new.

The secret is of type `kubernetes.io/basic-auth`. Details are at https://kubernetes.io/docs/concepts/configuration/secret/#basic-authentication-secret.

We'll have to turn this into a docker config entry. See `TransformProvV2RegistryCredentialsToDockerConfigJSON` for code to help with that.

Using a secret with a type of `kubernetes.io/basic-auth` means we should be able to re-use the existing secret. And, in our docs on using this with Fleet directly we can tell them how to create one of these secrets.

**Comment by Josh-Diamond** [comment] 2022-10-19 17:01
Duplicate of https://github.com/rancher/fleet/issues/948;

Issue will be further tracked there

**Comment by Josh-Diamond** [comment] 2022-10-19 17:07
Ticket #948 - Test Results
---

With HA Helm:

Veri-FAILED on rancher  `v2.7.0-rc4`:
1. Fresh install of rancher `v2.7.0-rc4`
2. Set a valid, unauthenticated global registry
3. Provision a downstream RKE2 AWS Node driver cluster w/ authenticated cluster registry configured and k8s `v1.24.6+rke2r1`
4. Veri-FAILED:
   - cluster successfully provisions
   - fleet-agent `ImagePullBackOff`
   - Failed to pull image from path: `cluster_registry/global_registry/rancher/fleet-agent:v0.5.0-rc2`
   - Image incorrectly formatted; expected to be: `cluster_registry/rancher/fleet-agent:v0.5.0-rc2`

**Comment by manno** [comment] 2022-10-26 11:43
@Josh-Diamond should I re-open the ticket, or are you going to re-open it when QA tests again?

**Comment by Josh-Diamond** [comment] 2022-10-26 20:32
Awaiting new fleet-RC to resume testing - [requested and pending]

**Comment by Josh-Diamond** [comment] 2022-10-27 22:21
RE-OPENED
---

Fleet version on `2.7-0247e139a4ba7f2473a0ad10c0e472f34d88fc6d-head` reflects `fleet:v0.5.0-rc3`;

Expected to be `fleet:v0.5.0-rc4`, as addressed in [PR-39439](https://github.com/rancher/rancher/pull/39439)

Unable to proceed w/ validations;  

Awaiting `fleet:v0.5.0-rc4`

**Comment by Josh-Diamond** [comment] 2022-10-28 19:11
Fleet-rc4 now available. Resuming testing efforts

**Comment by Josh-Diamond** [comment] 2022-10-28 19:32
Ticket #948 - Test Results - RE-OPENED
---

With HA Helm:

Veri-FAILED on rancher  `v2.7.0-rc4`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Provision a downstream RKE2 AWS Node driver cluster w/ global registry set and auth'd cluster registry configured | ✅ |
| 2. | Provision a downstream RKE1 AWS Node driver cluster w/ global registry set and auth'd cluster registry configured | :x: |

---

Scenario 1:
1. Fresh install of rancher `v2.7.0-rc8`
2. Set a valid, unauthenticated global registry
3. Provision a downstream RKE2 AWS Node driver cluster w/ authenticated cluster registry configured and k8s `v1.24.7+rke2r1`
4. Verified:
   - cluster successfully provisions
   - fleet-agent successfully deployed and pulling accurate image

---

❗  Scenario 2:
1. Fresh install of rancher `v2.7.0-rc8`
2. Set a valid, unauthenticated global registry
3. Provision a downstream RKE1 AWS Node driver cluster w/ authenticated cluster registry configured and k8s `v1.24.6-rancher1-1`
4. Veri-FAILED:
   - cluster successfully provisions
   - `fleet-agent` image is successfully pulled from global registry; expected to be cluster level registry

**Comment by mattfarina** [comment] 2022-11-01 14:13
@Josh-Diamond I tracked down the issue and found a Rancher internal bug. I filed an issue at https://github.com/rancher/rancher/issues/39468. It seems the provisioning system isn't syncing the registry to all the places it should so the creation of the fleet.Cluster does not have the needed information.

This appears to be an issue with Rancher provisioning rather than fleet. How should we proceed @sowmyav27 @bmdepesa

**Comment by Josh-Diamond** [comment] 2022-11-01 20:36
Moving issue to BLOCKED until https://github.com/rancher/rancher/issues/39468 is resolved

**Comment by Josh-Diamond** [comment] 2022-11-03 23:57
Ticket #948 - Test Results - [cont.]
---

With HA Helm:

Verified on rancher  `v2.7.0-rc9`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Provision a downstream RKE2 AWS Node driver cluster w/ global registry set and auth'd cluster registry configured | ✅ |
| 2. | Provision a downstream RKE1 AWS Node driver cluster w/ global registry set and auth'd cluster registry configured | ✅ |

---

Scenario 2:
1. Fresh install of rancher `v2.7.0-rc9`
2. Set a valid, unauthenticated global registry
3. Provision a downstream RKE1 AWS Node driver cluster w/ authenticated cluster registry configured and k8s `v1.24.6-rancher1-1`
4. Verified:
   - cluster successfully provisions
   - `fleet-agent` image is successfully pulled from cluster level registry; expected behavior

**Closed by Josh-Diamond** 2022-11-03 23:57 UTC
Labels: kind/enhancement, area/fleet, team/fleet
