### ISSUE TITLE
Delete clusterregistration upon deleting the custom rke1 downstream cluster 

### ISSUE THREAD

**Issue by skanakal** [rancher/fleet#1605] opened 2023-06-19 08:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently,  clusterregistration are not being cleaned up when a custom rke1 cluster is deleted.

### Expected Behavior

When a cluster is deleted in Rancher, all resources associated with the cluster clusterregistration should be properly cleaned up, ensuring a clean state and preventing any leftover artifacts.

### Steps To Reproduce

1. create a custom RKE1 cluster (Use existing nodes and create a cluster using RKE)
2. Wait for the cluster to become active.
3. Delete the cluster from Rancher UI.
4. Observe that clusterregistrations are not cleaned up from the fleet-default namespace.

### Environment

```markdown
- Architecture: x86_64
- Fleet Version: fleet-102.0.0+up0.6.0
- Cluster: RKE1 
  - Provider: custom
  - Options:
  - Kubernetes Version: v1.24.13-rancher2-1

Rancher version: 2.7.4
local cluster: v1.24.11+rke2r1
```

### Logs

```markdown
create custom rke1 downstream cluster from rancher UI:

~~~
newrancherserver:~ # kubectl get cluster -A
NAMESPACE       NAME      READY   KUBECONFIG
fleet-default   c-92zp4   true    c-92zp4-kubeconfig
fleet-local     local     true    local-kubeconfig
newrancherserver:~ # 
newrancherserver:~ # kubectl get clusterregistration -A
NAMESPACE       NAME            CLUSTER-NAME   LABELS
fleet-default   request-jvnq8   c-92zp4        {"management.cattle.io/cluster-display-name":"rkedscluster","management.cattle.io/cluster-name":"c-92zp4","objectset.rio.cattle.io/hash":"904865775b6bb389c7605c3879bedf5569e0fffb","provider.cattle.io":"rke"}
fleet-local     request-8q8st   local          {"name":"local","objectset.rio.cattle.io/hash":"67f475f626e5473772f6084a291170a9de5942d1"}
newrancherserver:~ # 
~~~

Delete the downstream cluster

~~~
newrancherserver:~ # kubectl get cluster -A
NAMESPACE     NAME    READY   KUBECONFIG
fleet-local   local   true    local-kubeconfig
newrancherserver:~ # 
newrancherserver:~ # kubectl get clusterregistration -A
NAMESPACE       NAME            CLUSTER-NAME   LABELS
fleet-default   request-jvnq8   c-92zp4        {"management.cattle.io/cluster-display-name":"rkedscluster","management.cattle.io/cluster-name":"c-92zp4","objectset.rio.cattle.io/hash":"904865775b6bb389c7605c3879bedf5569e0fffb","provider.cattle.io":"rke"}
fleet-local     request-8q8st   local          {"name":"local","objectset.rio.cattle.io/hash":"67f475f626e5473772f6084a291170a9de5942d1"}
newrancherserver:~ # 
~~~
```

### Anything else?

here is a  fix related to rke2 downstream cluster  https://github.com/rancher/fleet/pull/481/commits/db17d0bf7b88a6ab8a18633d2f7352dcc32ac9d9

**Comment by manno** [comment] 2023-07-21 13:19
closing as duplicate of https://github.com/rancher/fleet/issues/1656 even though it was first

**Closed by manno** 2023-07-21 13:19 UTC
Labels: [zube]: Done, kind/bug, area/fleet, team/fleet
