### ISSUE TITLE
[Question] Helm chart version override in fleet.yaml

### ISSUE THREAD

**Issue by romejoe** [rancher/fleet#899] opened 2022-08-03 21:26 UTC
Is it possible to override the version of a helm chart with a target customization? I have the following fleet.yaml file and the cluster that has the version change is still using the global version. Reading the documentation on fleet.yaml makes it seem like this is possible, but looking through the code, it seemed to me that it wasn't implemented to support that. I noticed some additional handling  [here](https://github.com/rancher/fleet/blob/4a771da9d42bc1fade1e4f41a9dce7ce85eccf12/pkg/bundle/resources.go#L55), but adding the repo and chart properties to the helm target customization caused the deploy to fail before generating any bundles.

```yaml
defaultNamespace: app
namespace: app

helm: 
  repo: https://registry.company.com/chartrepo/dev
  chart: app
  version: 1.0.0
  values:
    resources:
      enable: true
targetCustomizations:
  - name: cluster-a
    helm:
      valuesFiles:
        - cluster-a/values.yaml
    yaml:
      overlays:
        - cluster-a
    clusterSelector:
      matchLabels:
        cluster-name: cluster-a

  - name: cluster-b
    helm:
      version: 1.1.0
      valuesFiles:
        - cluster-b/values.yaml
    yaml:
      overlays:
        - cluster-b
    clusterSelector:
      matchLabels:
        cluster-name: cluster-b
  
```

**Comment by Shaked** [comment] 2022-08-16 11:43
I think it's duplicated? https://github.com/rancher/fleet/issues/344

**Comment by romejoe** [comment] 2022-08-17 02:37
@Shaked I think it’s different from #344.  On both of my clusters, a release was done. However, on cluster-b, instead of the version of the helm chart being 1.1.0, it was v1.0.0. Ultimately, I ended up multiple GitRepos and fleet.yamls to address this, which wasn’t ideal… 

I’m reading through the fleet source right now to make sure this issue isn’t duplicating #344.

**Comment by romejoe** [comment] 2022-08-17 02:55
My understanding of the difference between the two issues is this:
- #344 is running into an issue with having 2 target customizations matching a cluster, but the first customization is the only one used. All matching target customizations aren’t being deployed.
- This issue effectively wants to use a different chart entirely for a target customization(I didn’t realize that is basically what I’m trying to do until now), but share some helm values and other properties set in the fleet.yaml.

**Comment by Shaked** [comment] 2022-08-17 09:37
> My understanding of the difference between the two issues is this:
> 
> * [Deploy the same repo to the same namespace with different values via fleet.yaml #344](https://github.com/rancher/fleet/issues/344) is running into an issue with having 2 target customizations matching a cluster, but the first customization is the only one used. All matching target customizations aren’t being deployed.
> * This issue effectively wants to use a different chart entirely for a target customization(I didn’t realize that is basically what I’m trying to do until now), but share some helm values and other properties set in the fleet.yaml.

Basically the `version` keyword doesn't work for either your or my case. I think that the reason is the same, even if the use case is different.

**Comment by romejoe** [comment] 2022-08-17 14:58
Ah ok, now I see where you were changing versions later in the comments. I think I may see where the version is being ignored in the code. I'll try to take a closer look at it and experiment tonight. That trivy test you added will be helpful for that. I doubt the fix I'm thinking of will fix the issue of multiple deployments to the same cluster though

**Comment by Martin-Weiss** [comment] 2022-09-27 10:06
@romejoe - I am running into the same issue, here. See i.e. https://github.com/Martin-Weiss/rancher-fleet/blob/main/rke-cert-manager/app/fleet.yaml where I need to deploy different versions to different clusters. Unfortunately only the "global" version seems to be taken and the "targetCustomization" version is ignored. 
Did you work on this issue in the meantime?

**Comment by romejoe** [comment] 2022-09-27 11:29
I haven’t had a chance to look into this issue any further yet because work and life came up but I can try to look into this more later today. As I recall, I think it was kind of a simple change, so I’ll try to see if I can get something working and tested on my dev clusters.

**Comment by romejoe** [comment] 2022-09-28 05:35
I did some additional testing with a couple different basic configs(see [here](https://github.com/romejoe/fleet-test/blob/main/multi-chart-test/fleet.yaml) if interested) with the latest code on master after looking at the source to see if any of them would work as expected but none did. I'm still experimenting to see what I can come up with.

**Comment by mattfarina** [comment] 2022-09-29 18:07
Is this a duplicate of #699

**Comment by romejoe** [comment] 2022-09-30 07:56
I was incorrect with my earlier comment about there being an issue with some other components. I didn't fully understand and misunderstood the function at the time.

The fix turned out to be fairly simply(a bit frustrating to get quite right though). I have the pull request submitted and I've tested it on my personal dev clusters.

**Closed** 2022-11-04 07:09 UTC
Labels: area/fleet, team/fleet
