### ISSUE TITLE
[SURE-9155] Alignment of the sync behaviour of labels and annotations

### ISSUE THREAD

**Issue by drasang** [rancher/fleet#1584] opened 2023-06-09 13:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently it seems that only labels from the `v3/clusters` are synced to the corresponding `fleet.cattle.io.clusters` object. 
Changes to the annotations are not synced. 

This also causes changes to annotations via editing the cluster resource in the Rancher UI under `/dashboard/c/local/fleet/fleet.cattle.io.cluster` to only be reflected in `v3/cluster`.

Since this behaviour differs from the known behaviour of the labels, this leads to mistakes like those seen in Issue #1516. 
Contrary to the assumption and changes made in the UI, no annotation has been configured on the fleet cluster object that could be referred to in the template.

### Expected Behavior

As with labels, the user-defined annotations are synchronised from the `v3/clusters` object to the corresponding Fleet object. 

### Steps To Reproduce

* Create a cluster in Rancher
* Edit the cluster in the UI under "Contionues Delivery" -> "Clusters" using "Edit Config".
* Add labels and annotations and save the changes.

* Using the browser's developer tools, it can be seen that two PUT requests have been made against `/v3/clusters/clusterid` and `v1/fleet.cattle.io.clusters/fleet-default/clusterid`. 
The request against `/v3/clusters` contains the newly configured annotations and labels. The request against Fleet does not contain these.

* Display the Fleet Cluster Object, either via the UI as YAML (Download/Edit YAML) or via kubectl: `kubectl get clusters.fleet.cattle.io -n fleet-default -oyaml <clusterid>`
* The object only has the new labels, the annotations have not been added. Since the previous request did not add the labels to the fleet object directly, but they are now present, indicates that they are being synchronised from `v3/clusters`. 

### Environment

```markdown
* Architecture: amd64
* Fleet Version: 0.6.0
* Rancher Version: 2.7.4
* Management Cluster: 
  * Provider: EKS
  * Version: 1.24
* Downstream Cluster: 
  * Provider: EKS (Imported)
  * Kubernetes Version: 1.23/1.24
```

### Anything else?

Workaround:
The cluster resource can be edited via "Edit Yaml". 
In this case, the PUT request is only sent to `v1/fleet.cattle.io.clusters/fleet-default/clusterid` and this time also contains the labels and annotations.

**Comment by weyfonk** [comment] 2024-10-01 07:11
### Problem
Updating annotations on a cluster through the Rancher UI would not be reflected in the corresponding Fleet cluster resource, although propagation of updates did work for labels.
 
### Solution
Added annotations to fields taken into account when creating a Fleet cluster object.
 
### Testing
See repro steps above

### Engineering Testing
#### Manual Testing
Tested reproduction steps before and after the change, noticing that in the latter case.

#### Automated Testing
Added unit tests to Rancher covering cluster creation (which seems to be also run upon updating a cluster in the UI) and validating actual vs expected labels and annotations.

### QA Testing Considerations
Verify that update and deletion of labels through the UI works as expected, propagating changes to the corresponding Fleet cluster resource.
 
#### Regressions Considerations
N/A

**Comment by sbulage** [comment] 2024-10-04 15:59
### QA Observations
I have created a video which covers the detailed steps which I performed. In order to check the label/annotations on propagation from Fleet cluster to Management cluster.

### Videos

<details>
<summary>Video showing detailed steps</summary>

https://github.com/user-attachments/assets/770f0149-2a9a-4de8-98c4-33502f631112

</details>

**Comment by weyfonk** [comment] 2024-10-07 15:03
Apologies. I'd merged a fix into `rancher/rancher`'s `main`, ie targetting Rancher v2.10.0 instead of v2.9.3 which was the original target milestone for this issue.
Please validate this against v2.10.0.

[This issue](https://github.com/rancher/fleet/issues/2937) and the PR linked there target Rancher v2.9.3.

**Comment by sbulage** [comment] 2024-10-31 07:09
### System Information

| Rancher Version | Fleet Version |
|--------|--------|
| **v2.10.0-alpha5** | **fleet:v0.11.0-beta.3** | 

---

### Scenario performed.
- Labels and annotations are updated from Continuous Delivery --> Clusters are updated to the Management clusters and _vice-versa_
- Same procedure performed via API `PUT` method and it did worked.
- Labels and Annotations updated via API endpoints are reflected on same cluster under Fleet Clusters and Management clusters.

_**I have recorded video to show the steps which I performed.**_

---

### Video:
<details>
<summary><b>Video shows the annotation via UI and API endpoints.</b></summary>



</details>

**Closed** 2024-10-31 07:11 UTC
Labels: kind/bug, JIRA
