### ISSUE TITLE
How to Scale up fleet-controller? 

### ISSUE THREAD

**Issue by ritheshgm** [rancher/fleet#319] opened 2021-03-31 16:11 UTC
How to scale up fleet-controller? When we try to increase the replicas we will be getting below error and due to which one pod running as a leader and taking nearly 40mins per cluster to deploy the fleet-agent in downstream cluster. 

Since we are managing 2000 cluster it's difficult to manage with one leader. 

error : 
time="2021-03-31T15:37:40Z" level=info msg="No access to list CRDs, assuming CRDs are pre-created."
I0331 15:37:41.325018       1 leaderelection.go:243] attempting to acquire leader lease fleet-system/fleet-controller-lock...

**Comment by vijaytrainer** [comment] 2021-03-31 18:24
+1

**Comment by nickgerace** [comment] 2021-03-31 20:28
Hi @ritheshgm - I spoke with @StrongMonkey and want to know more about where the bottleneck may be.
Only one leader is used because only one leader can do the controller sync.

@ibuildthecloud tested fleet with 1 million clusters; perhaps, this post may contain helpful information: https://rancher.com/blog/2020/scaling-fleet-kubernetes-million-clusters

This could be an `etcd` bottleneck, but I'm unsure at this point. The controller should already be scalable, so I'm curious what is happening exactly.

**Comment by ritheshgm** [comment] 2021-04-01 07:38
Hi Nick, Thanks for your response.

We are managing 2000+ cluster in a rancher. we are building rke cluster and importing to Rancher through terraform. 

Issue 1: Once the cluster is added to rancher its taking 10mins time to show the node count in the rancher cluster manager 
Issue 2: Taking 20mins time for fleet agent to get install on the cluster. 

We have updated the parameters which are mentioned in this post. But nothing helped. 
https://rancher.com/blog/2020/scaling-fleet-kubernetes-million-clusters

Also verified etcd logs we have a enough size and no errors found.

**Comment by nickgerace** [comment] 2021-04-06 19:45
Hi @ritheshgm - thank you very much for the feedback and your patience. We are keeping an eye on this, so that context helps a lot.

> Issue 1: Once the cluster is added to rancher its taking 10mins time to show the node count in the rancher cluster manager
> Issue 2: Taking 20mins time for fleet agent to get install on the cluster.

Rancher clusters should be provisioned in under 15 minutes, so these two issues are not unexpected. Rancher being a "bottleneck" here is to be expected.

However, bottlenecks in the 1hr+ range can definitely be an issue. We will keep an eye on this. Thank you.

**Comment by ritheshgm** [comment] 2021-04-07 09:32
Hi @nickgerace, Thanks for your response. 

After adding 350+ clusters to rancher now its taking more than 4 hours and sometimes it takes 12hrs to import the cluster (show up the node information) and this is inconsistent now even if we rebuild 1 cluster also its take 6 hrs to see the those information. After we see the node information fleet is getting deploy. 

So basically it take more than 12hrs to see the application deployed through fleet. 

To precise, the cattle-credential patching with the namespace name as clusterID to cluster-agent  in downstream clusters is not happening..

**Comment by nickgerace** [comment] 2021-04-07 21:44
Hi @ritheshgm - we really appreciate the details. That is very likely unintended behavior. We are validating if this issue has been seen anywhere else. I'll update this issue if/when our findings include anything substantial.

**Comment by vijaytrainer** [comment] 2021-04-09 11:47
@nickgerace Following issue is raised under rancher

https://github.com/rancher/rancher/issues/31938

**Comment by dramich** [comment] 2021-04-09 14:05
@ritheshgm Based on your description I believe this is actually [this](https://github.com/rancher/rancher/issues/31999) issue and is caused by rancher, not by fleet, so I am going to close this issue.

**Closed by dramich** 2021-04-09 14:05 UTC
