### ISSUE TITLE
[v0.5] Backport #1161 to Rancher 2.6

### ISSUE THREAD

**Issue by thardeck** [rancher/fleet#1200] opened 2022-12-20 15:47 UTC
Linked issue: SURE-5496

Commit to backport: https://github.com/rancher/fleet/pull/1181/commits/75f0cf871178380b2e78334abf6a9ee14badf534

Refers to rancher/fleet#1161 

**Edited on 2023-01-26**

### Problem

In Rancher v2.6.9 GitRepos containing a Fleet yaml with an image scan specification (https://fleet.rancher.io/imagescan) are stuck in an Error state with a  message of the format `mkdir /tmp/fleet-default-test3109007355: read-only file system`, although the bundle itself appears successfully deployed. This seems likely to be a result of the work done for https://github.com/rancher/fleet/issues/845
 
### Solution

Use known_hosts provided by ssh secret for go-git the same way it is used for gitjob. This allows SSH based GIT connections.

The SSH private key and known_hosts can be provided as clientSecretName like this:
e. g.: kubectl create -n fleet-local secret generic <CLIENT_SECRET_NAME> --type kubernetes.io/ssh-auth --from-file=ssh-privatekey="<PRIVATE_KEY_PATH>" --from-file=known_hosts="<KNOWN_HOSTS_PATH>"
 
### Testing
< Note: Confirm if the repro steps in the GitHub issue are valid, if not, please update the issue with accurate repro steps. >

#### Manual Testing

Deploy a Rancher v2.6.9 instance with a single all-role node custom cluster (I used github.com/superseb/tf-do-rancher2)
In the Continuous Delivery UI add a GitRepo with a fleet.yaml containing an image scan specification (https://fleet.rancher.io/imagescan). I used the 00373641 branch of https://github.com/axeal/fleet-test.git
Whilst the Bundle is successfully deployed, observe errors of the following format in the fleet controller Pods logs `time="2022-10-31T11:10:59Z" level=error msg="error syncing 'fleet-default/test': handler image-sync: mkdir /tmp/fleet-default-test852371953: read-only file system, requeuing"` and the GitRepo is in an error state with a message of the format `mkdir /tmp/fleet-default-test3109007355: read-only file system` 

#### Automated Testing

e2e tests have been added to cover this issue. cfr e2e/require-secrets/imagescan_test.go

### QA Testing Considerations
/
 
#### Regressions Considerations

/

**Comment by olblak** [comment] 2023-01-26 10:45
@thardeck Do you have a QA template or a way to test this issue?

**Comment by olblak** [comment] 2023-01-26 11:04
This code related to this issue is on https://github.com/rancher/fleet/pull/1202 and we think it's small enough that we don't need QA validation. Additional information about how to test this issue would be great

**Comment by sowmyav27** [comment] 2023-01-26 15:38
@olblak Can you let us know what the issue is to understand what to test ?

**Comment by olblak** [comment] 2023-01-26 16:22
@sowmyav27 I just updated this issue body based on the Jira and PR information

**Comment by sowmyav27** [comment] 2023-02-07 03:39
@kkaempf Can we please add a QA Template for this issue?

**Comment by kkaempf** [comment] 2023-02-07 08:35
> @kkaempf Can we please add a QA Template for this issue?

Citing from https://github.com/rancher/fleet/issues/1200#issue-1504780536

> Engineering Testing
> Manual Testing
> 
> Deploy a Rancher v2.6.9 instance with a single all-role node custom cluster (I used github.com/superseb/tf-do-rancher2)
> In the Continuous Delivery UI add a GitRepo with a fleet.yaml containing an image scan specification (https://fleet.rancher.io/imagescan). I used the 00373641 branch of https://github.com/axeal/fleet-test.git
> Whilst the Bundle is successfully deployed, observe errors of the following format in the fleet controller Pods logs time="2022-10-31T11:10:59Z" level=error msg="error syncing 'fleet-default/test': handler image-sync: mkdir /tmp/fleet-default-test852371953: read-only file system, requeuing" and the GitRepo is in an error state with a message of the format mkdir /tmp/fleet-default-test3109007355: read-only file system
> Automated Testing
> 
> e2e tests have been added to cover this issue. cfr e2e/require-secrets/imagescan_test.go

Closing as fixed since "e2e tests have been added to cover this issue."

**Closed by kkaempf** 2023-02-07 08:35 UTC
Labels: [zube]: Reopened, area/fleet, team/fleet, JIRA, status/needs-qa-test-template
