### ISSUE TITLE
Feature Request: Automatically force sync BundleDeployments in Modified state

### ISSUE THREAD

**Issue by skaven81** [rancher/fleet#1554] opened 2023-05-24 20:12 UTC
### Is your feature request related to a problem?

An important and crucial feature of any configuration management system is _convergence_ -- the natural tendency of such a system to "heal" its way toward a desired state, and to stay that way through idempotent changes.

Flux, Argo, and virtually all other CD tools out there have the ability to treat a git repository as the canonical desired state, and to forcibly ensure that software deployments always match the upstream canonical configuration.

Fleet, however, lacks this feature, meaning that if a Bundle deployed to a downstream cluster gets modified, Fleet just marks it as `Modified` and stops applying updates.  It then requires a manual touch to force a resync of that BundleDeployment to get it back into a desired state.

This is problematic for several reasons:
* Fleet cannot be trusted for security-sensitive deployments, as cluster-local changes/overrides don't get repaired.  An attacker could modify a Fleet-managed resource and Fleet just shuts down instead of trying to resolve the problem.
* When deploying at scale, there will inevitably be occasional glitches and naiive admins that collectively cause configuration to drift.  Since Fleet requires manual intervention to resolve this drift, scaling up is more difficult or requires additional work.
* It demonstrates a lack of feature parity with industry-standard tools like Argo and Flux

### Solution you'd like

The `fleet.yaml` spec should be extended to include a `forceResync` attribute, which defaults to `false` (the current behavior).  If set to `true`, then any time a deployment of that Bundle goes into a Modified state, `fleet-agent` will force a resync to bring the deployment back into compliance with the upstream git repository.

It would be equally useful to have `forceResync` be an attribute of a GitRepo -- with the same behavior as above, only it applies to all the Bundles listed in the GitRepo spec.

Having both would be best, but I'd be happy with either.

As a bonus extension to just having a `forceResync` option, being able to tweak the behavior of resyncing would be great.  For example, being able to configure how long the BundleDeployment has to be in Modified state before forcing a sync, configuring how frequently it's allowed to try resyncing (perhaps using an exponential back-off mechanism), and a time or count limit for resyncs before fleet-agent just gives up and puts the BundleDeployment into some kind of an error state such as `ModifiedCannotResync`.

### Alternatives you've considered

In the absence of a Fleet-managed auto-resync functionality, the best/only option I've considered is writing my own controller that watches BundleDeployment resources and upon seeing one go into a `Modified` state, automatically increment the `forceSyncGeneration` attribute to trigger a resync.  This is an extreme solution though for something that should be a table-stakes feature of any CD tool.

**Comment by eumel8** [comment] 2023-07-26 15:16
@skaven81 is your own controller ready to test? Would be happy to try out any other solution to repair that simple workflow from Fleet.

**Comment by skaven81** [comment] 2023-07-26 15:59
@eumel8  I have not implemented such a controller.  Still hoping that SUSE gives us a way to force modified Bundles back into compliance.

**Comment by iosifnicolae2** [comment] 2023-08-04 19:01
It would be great to have an option to `forceResync` in the Fleet UI so we can perform this operation manually.

**Comment by manno** [comment] 2023-08-21 12:15
I believe this will be in the upcoming [v0.8](https://github.com/rancher/fleet/releases/tag/v0.8.0-rc.2).

I would close this issue as a duplicate of https://github.com/rancher/fleet/issues/1551?

**Comment by skaven81** [comment] 2023-08-30 20:16
Yes it does look like https://github.com/rancher/fleet/pull/1594 implements this feature.

**Closed** 2023-09-12 12:29 UTC
Labels: [zube]: To Triage, kind/enhancement, area/fleet, team/fleet, kind/duplicate
