### ISSUE TITLE
Add age and actual resource list per cluster to status

### ISSUE THREAD

**Issue by kkaempf** [rancher/fleet#1184] opened 2022-12-16 15:46 UTC
### SURE-4651

From rancher/rancher#36173

> See UI ticket: https://github.com/rancher/dashboard/issues/4683
> 
> There is a request to show the age and last modified date of resources in the Dashboard UI for fleet. Currently this data is not available from fleet.
> 
> Can we add to the response ofthe `/v1/fleet.cattle.io.gitrepos/WORKSPACE/REPO` API this metadata for each of resources in the resources list.
> 
> SURE-4651

**Comment by kkaempf** [comment] 2023-01-10 13:30
Probably a UI design problem - needs help from UI engineer

**Comment by manno** [comment] 2023-05-11 13:23
This is a duplicate of https://github.com/rancher/rancher/issues/36173

**Comment by manno** [comment] 2023-05-24 17:30
The resources tab exists for 
- gitrepo: shows the .status.resources key
- bundle: shows the .status.resourceKey key

The gitrepo's `resources` key is calculated from the aggregated `resourceKey`s of its bundles. This happens after the bundles are created. The resources that are listed are not the actual resources which were deployed to clusters. It's an early estimation, that doesn't take targeting (bundledeployments) into account.
The actual list of resources can differ, for example because a helm chart uses capabilities to deploy different resources, depending on the k8s version. Also target customizations and overlays may affect the outcome for some clusters.

To provide timestamps and an accurate list (bundle, cluster), we would need to send the helm release information from the downstream cluster and store it on the bundledeployment.

**Comment by manno** [comment] 2023-06-20 10:22
We can't easily add an "updated at" timestamp to the resources. 
It’s not something that k8s provides in a unified way. Other projects like k9s just report the creation date as "age", for example [pvc](https://github.com/derailed/k9s/blob/master/internal/render/pvc.go#L75).

It's unclear how special handling would look like, what is the "updated at" of a pod? Probably some field from its status, but adding a label to a pod doesn't change any of the timestamps.

**Comment by sbulage** [comment] 2023-06-30 06:11
Hello @manno is this fix not in the fleet version `0.8.0-rc.1`?

**Comment by raulcabello** [comment] 2023-07-11 16:08
> @manno I do check the [entities](https://github.com/rancher/fleet/pull/1596/files#diff-10d022afcad3a9d832fea7576ff54111e096fc75f19fdf928abb873b17f20cdaR203-R208) are present there or not, following is my observations:
> 
> ```
> Status:
>   Ready:         true
>   Release:       nginx-override/testing-time-overrride-targets:2
>   Resources:
>     API Version:    apps/v1
>     Created At:     <nil>
>     Kind:           Deployment
>     Name:           nginx-donot-deploy
>     Namespace:      nginx-override
>   Sync Generation:  0
> Events:             <none>
> ```
> 
> I see it shows the `Created At: <nil>` can you please take a look at it?

I see the same problem. I think it is because we get the resources from the helm release manifest, therefore the creation timestamp is not set.

**Comment by gaktive** [comment] 2023-07-12 19:37
UI done what they can in https://github.com/rancher/dashboard/issues/4683 -- we still await the endpoint returning the appropriate data on the backend.

**Comment by sbulage** [comment] 2023-07-24 07:56
@manno #1653 is available in latest fleet `rc` build ?

**Comment by manno** [comment] 2023-07-24 09:59
## Additional QA
 
### Problem

The existing resource list (`resourceKey` on `bundle.Status`) is only an estimate. This adds the real deployed resources per cluster.

 
### Solution

fleet-agent adds the list of deployed resources to the bundle deployment resource on the management cluster.
It also adds the creation time of the resources.

### Testing

### Engineering Testing
#### Manual Testing

Verified manually that a resource list is added to bundledeployments, after they're deployed.

#### Automated Testing

Existing integration test was extended to include a check for the new resource list status field and the existence of the time stamp.

### QA Testing Considerations

Generated resources, i.e. from a job that's within the bundle won't be included in the list.
 
#### Regressions Considerations

The change does not query the cluster for resources, instead it uses the existing list from `apply`. This is good for performance and should still be accurate, even when updating an existing release.

**Comment by sbulage** [comment] 2023-08-07 09:05
**QA TEST PLAN**

Scenarios
|Scenario|Test Case|
|---|---|
|1| Test `BundleDeployment` has `API Version, Created At, Kind, Name and Namespace` under `status.resource` via CLI.
|2| Test `BundleDeployment` has `API Version, Created At, Kind, Name and Namespace` under `status.resource` via CLI after upgrade.

**Comment by sbulage** [comment] 2023-08-07 10:25
**TEST RESULT**
Scenarios
|Scenario|Test Case|Results
|---|---|---|
|1| Test `BundleDeployment` has `API Version, Created At, Kind, Name` and `Namespace` under `status.resource` via CLI.|:heavy_check_mark:|
|2| Test `BundleDeployment` has `API Version, Created At, Kind, Name` and `Namespace` under `status.resource` via CLI after upgrade.|:heavy_check_mark:|


**REPRO STEPS**

**Scenario 1**
1. Add `GitRepo` and wait for sometime to create the resources.
2. Check the `BundleDeployment` is created and all resources are created in the cluster.
3. Verified that `API Version, Created At, Kind, Name` and `Namespace` is present in the `BundleDeployment`.
    - Executed below command to check `BundleDeployment` has all attributes.
    ```
    kubectl get bundledeployments.fleet.cattle.io -n cluster-fleet-default-imported-cluster-1-0e23167da219   test-fleet-examples-simple -o json | jq -r '.status.resources'
    ```
<details>

**<summary>Command Output: </summary>**
    
      ```
      [
        {
          "apiVersion": "apps/v1",
          "createdAt": "2023-07-26T17:18:53Z",
          "kind": "Deployment",
          "name": "frontend",
          "namespace": "default"
        },
        {
          "apiVersion": "apps/v1",
          "createdAt": "2023-07-26T17:18:53Z",
          "kind": "Deployment",
          "name": "redis-master",
          "namespace": "default"
        },
        {
          "apiVersion": "apps/v1",
          "createdAt": "2023-07-26T17:18:53Z",
          "kind": "Deployment",
          "name": "redis-slave",
          "namespace": "default"
        },
        {
          "apiVersion": "v1",
          "createdAt": "2023-07-26T17:18:53Z",
          "kind": "Service",
          "name": "frontend",
          "namespace": "default"
        },
        {
          "apiVersion": "v1",
          "createdAt": "2023-07-26T17:18:53Z",
          "kind": "Service",
          "name": "redis-master",
          "namespace": "default"
        },
        {
          "apiVersion": "v1",
          "createdAt": "2023-07-26T17:18:53Z",
          "kind": "Service",
          "name": "redis-slave",
          "namespace": "default"
        }
      ]
      ```
</details>

**Scenario 2**
1. Add `GitRepo` and wait for sometime to create the resources in older version of fleet.
2. Check the `BundleDeployment` is created and all resources are created in the cluster.
3. Verify that there is no information about `API Version, Created At, Kind, Name` and `Namespace` is present in the `BundleDeployment`.
4. Upgrade Rancher/Fleet and wait for it to finish.
5. Verified that `API Version, Created At, Kind, Name` and `Namespace` is present in the `BundleDeployment`.
    - Executed below command to check `BundleDeployment` has all attributes.
    ```
    kubectl get bundledeployments.fleet.cattle.io -ncluster-fleet-default-imported-cluster-1-0e23167da219   test-test-test-test-test-test-test-test-test-t-a4fd0 -o json | jq -r '.status.resources'
    ```
    - Output:
      ```
      [
        {
          "apiVersion": "apps/v1",
          "createdAt": "2023-07-27T08:25:34Z",
          "kind": "Deployment",
          "name": "nginx-myapp",
          "namespace": "default"
        }
      ]
      ```

**Closed** 2023-08-07 10:25 UTC
Labels: kind/good-first-issue, kind/enhancement, status/dev-validate, area/ui, area/fleet, team/fleet, area/api, JIRA
