### ISSUE TITLE
Expose new EnableDNS property in Helm through fleet.yaml

### ISSUE THREAD

**Issue by mattfarina** [rancher/fleet#1332] opened 2023-02-16 21:02 UTC
The [Helm v3.11.1 release](https://github.com/helm/helm/releases/tag/v3.11.1) introduced a new flag/property. When Fleet updates to this version of Helm is should expose this property (which defaults to false) so that it can optionally be enabled. Prior to 3.11.1 the property did not exist and was the equivalent of setting it to true.

**Comment by manno** [comment] 2023-05-08 16:29
Fleet set `EnableDNS=true` to stay backward compatible with charts. Not sure what value it would provide to make this configurable.

**Comment by manno** [comment] 2023-05-09 10:57
This might actually fix #1430

**Comment by manno** [comment] 2023-08-21 12:17
closing as duplicate of #1430

**Comment by manno** [comment] 2023-09-04 10:19
not a duplicate

**Closed** 2023-09-11 09:35 UTC
Labels: area/fleet, team/fleet
