### ISSUE TITLE
Templating Helm Values in fleet.yaml

### ISSUE THREAD

**Issue by manno** [rancher/fleet#1164] opened 2022-12-08 10:16 UTC
## Additional QA

The feature was implemented in multiple PRs, so I'll add the QA info here.
 
* https://github.com/rancher/fleet/pull/671
* https://github.com/rancher/fleet/pull/1158

### Problem

There are two ways to modify deployments per target cluster: target customizations and cluster label replacement.

Creating [target customizations](https://fleet.rancher.io/gitrepo-structure#reference) to overwrite the helm values at the root can be tedious for a large number of clusters.  

Adding the value of a cluster label to the `helm.values` section of `fleet.yaml` is not flexible, e.g. it's not possible to prefix the result.  The amount of data stored in a label value is limited.

### Solution

The helm values section in `fleet.yaml` is now a template. Go and sprig template functions can be used to produce values for helm templates.

Additionally, values from the cluster resource (`spec.templateValues`) are passed into the template to produce cluster dependent helm values.

Note, this is limited to helm-type bundles, manifests and kustomize bundles don't use the helm values section. 
And `helm.valuesFrom` is not templated, the configmap, secrets are on downstream clusters, the templating happens before creating the bundle deployment on the upstream cluster. 
However, any `helm.valuesFiles` are in the bundle and their values will be templated. 

The `fleet.yaml` has to be valid YAML, so not all templating constructs one knows from, for example, helm will work. In a helm `templates/` folder, it's possible to [generate YAML with `with` and `range`](https://github.com/rancher/fleet-examples/blob/test-cluster-values/single-cluster/helm-cluster-values/templates/deployment.yaml#L34-L36). In `fleet.yaml` this will only work in multi-line strings.

Writing valid templating code is the users responsibility, templates with errors won't produce new bundledeployments.

#### Manual Testing

* Add labels and `templateValues` to a fleet cluster resource.
* Deploy with a fleet.yaml that has a 'helm.values' section with templating instructions to use the values from the cluster resource.
* Should work in root values and in overwritten values from a target customization.

Example: https://github.com/rancher/fleet-examples/blob/test-cluster-values/single-cluster/helm-cluster-values/fleet.yaml
Documentation: https://fleet.rancher.io/next/gitrepo-structure#reference

#### Automated Testing

* [Unit test for template processing](https://github.com/rancher/fleet/blob/master/pkg/target/target_test.go)
* [E2E test](https://github.com/rancher/fleet/blob/master/e2e/single-cluster/helm_verify_test.go#L54-L100)

### QA Testing Considerations

It's not necessary to test all possible template functions and advanced templating use cases. It's expected that users mostly use templating to set default strings and modify/prefix string values.
 
#### Regressions Considerations

Cluster label replacement (using the replacement string `global.fleet.clusterLabels.LABELNAME`) should still work.

**Comment by manno** [comment] 2023-01-26 10:21
This will not  be backported to 0.5.2 due to time constraints.

**Comment by olblak** [comment] 2023-01-26 10:22
Assigning this issue to the milestone [2023-Q1-v2.7x](https://github.com/rancher/fleet/milestone/19) as the team won't have the time before

**Comment by olblak** [comment] 2023-02-08 16:15
Is related to https://jira.suse.com/browse/SURE-5326

**Comment by sowmyav27** [comment] 2023-02-08 16:19
Since there is Automated tests around this, QA will pick this up for validations, in the end (lower priority)

**Comment by MSpencer87** [comment] 2023-04-05 16:19
Verified on Fleet 102.0.0+up0.6.0-rc.5

Template functions can be used to produce values for helm template strings and modify/prefix string values.


Steps to reproduce:

1) Bring up HA Rancher setup on 2.6.4 with a downstream cluster, confirm fleet verison 0.3.9
2) Fork the fleet-examples repo https://github.com/rancher/fleet-examples and create a new branch from single-cluster/helm-cluster-value and/or single-cluster/hel-template-values for testing
3) Navigate to Continuous Delivery via UI, select Git Reops and then select Create
4) Edit the fleet.yaml to remove `${ uuidv4 }` from  `namespace: ${ .ClusterNamespace }`
5) Enter a name, the forked repository URL and the name of the test branch. Add proper path `/single-cluster/test-branch-name` and select Create
6) Adding this repo will fail to deploy with error
```
Template: sleeper-chart/templates/deployment.yaml:34:47: executing "sleeper-chart/templates/deployment.yaml" at <.Values.hostnames>: range can't iterate over ${ list "one" "two" "three" | uniq | toJson }
```


Steps to validate:

1) Bring up HA Rancher setup on 2.7.2-rc8 with a downstream cluster, confirm fleet verison 102.0.0+up0.6.0-rc.5
2) Fork the fleet-examples repo https://github.com/rancher/fleet-examples and create a new branch from single-cluster/helm-cluster-value and/or single-cluster/helm-template-values for testing
3) Edit the fleet.yaml to remove `${ uuidv4 }` from  `namespace: ${ .ClusterNamespace }`
4) Navigate to Continuous Delivery via UI, select Git Reops and then select Create
5) Enter a name, the forked repository URL and the name of the test branch. Add path `/single-cluster/test-branch-name` and select Create
6) Confrm test chart depoloyment is successful inside the downstream cluster
7) Confirm git repo reaches Active state with Clusters Ready 1/1
8) Confrim bundle is created with no errors and reaches Active state

**Closed by MSpencer87** 2023-04-05 16:19 UTC
Labels: [zube]: QA Working, kind/enhancement, area/fleet, team/fleet, area/templating, JIRA
