### ISSUE TITLE
Editing an AKS cluster's cluster resource in Fleet results in removal of all user labels from cluster

### ISSUE THREAD

**Issue by SheilaghM** [rancher/fleet#669] opened 2021-12-04 00:30 UTC
SURE-3683

SUSE Rancher 2.6.2

Issue description:
User unable to add labels to an AKS cluster via Cluster Management or Continous Delivery UIs, post-cluster-creation/import in Rancher, and labels are reset upon an attempt to edit the Cluster via Continuous Delivery UI.

Business impact:
For a user making use of ClusterGroups and label selectors in Fleet this results in the removal of all Fleet deployed bundles from clusters once labels are lost.

Troubleshooting steps:
N/A

Repro steps:

- Provision a Rancher v2.6.2 instance
- Provision an AKS cluster and add a single label oncreate: foo (or import an pre-provisioned AKS cluster adding a label on import)
- Observe the presence of the oncreate: foo label on the cluster post-provisioning
- Navigate to Cluster Management -> click on the elipses for the AKS cluster and 'Edit Config'
- Attempt to add a new label postcreate: foo
- Observe the postcreate: foo label is absent on the cluster
- Edit the AKS cluster.management.cattle.io resource via kubectl in the local Rancher instance and add a label byyaml: foo
- Observe the byyaml: foo label is present on the cluster
- Navigate to the Continous Delivery UI -> fleet-default workspace -> Clusters, click the elipses for the AKS cluster and click 'Edit Config'
- Attempt to add a new label byfleet: foo
- Observe all users labels are removed from the cluster
- Actual behavior:
- User unable to add labels to AKS cluster via Cluster Management or Continous Delivery UIs, post-cluster-creation/import into Rancher, and labels are reset upon an attempt to edit the Cluster via the Continuous Delivery UI

Expected behavior:
User able to successfully add labels to the cluster via the Cluster Management or Continuous Delivery UIs, and editing the cluster via the Continuous Delivery UI does not result in unexpected removal of labels.

Files, logs, traces:
N/A

See SURE ticket for possible relation to an EKS issue.

**Comment by prachidamle** [comment] 2022-04-08 20:02
I have tested adding/removing labels on v3.cluster and see them reflect on the fleet cluster correctly for an RKE1 cluster. I do not see the problem of labels getting removed for RKE1 clusters.
I feel this might be specific to EKS cluster controllers. (or KEV2 controller logic?)

**Comment by manno** [comment] 2022-11-09 14:19
We couldn't reproduce this issue and suspect it's somewhere in the UI and syncing of provisioning resources. We're closing this for now, feel free to re-open .

**Closed by manno** 2022-11-09 14:19 UTC
Labels: good-first-issue, [zube]: Next Up, internal, area/fleet, team/fleet
