### ISSUE TITLE
Deploying the multi-cluster kustomize example results in bundle render error

### ISSUE THREAD

**Issue by janeczku** [rancher/fleet#236] opened 2021-01-22 14:07 UTC
Steps to reproduce:

1. Label a cluster with "env=dev"
2. Create a GitRepo via the UI pointing to the [Multi-Cluster Kustomize Example folder.](https://github.com/rancher/fleet-examples/tree/master/multi-cluster/kustomize)

```YAML
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: kustomize
  namespace: fleet-default
spec:
  repo: https://github.com/rancher/fleet-examples
  paths:
  - multi-cluster/kustomize
  targets:
  - name: dev
    clusterSelector:
      matchLabels:
        env: dev
```

**Expected:**

App is deployed to the cluster labeled "env=dev"

**Actual:**
App is not deployed. Bundle is stuck in error.

> error while running post render on files: Object 'Kind' is missing in '{"resources":["frontend-deployment.yaml","frontend-service.yaml","redis-master-deployment.yaml","redis-master-service.yaml","redis-slave-deployment.yaml","redis-slave-service.yaml"]}'

**Environment:**
Rancher v2.5.5

**Export of failing bundle:**

```
apiVersion: fleet.cattle.io/v1alpha1
kind: Bundle
metadata:
  creationTimestamp: "2021-01-22T13:56:00Z"
  generation: 1
  labels:
    fleet.cattle.io/commit: c6e54d7a56565e52a63de8a2088997b46253c1fb
    fleet.cattle.io/repo-name: test123
  managedFields:
  - apiVersion: fleet.cattle.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:fleet.cattle.io/commit: {}
          f:fleet.cattle.io/repo-name: {}
      f:spec:
        .: {}
        f:namespace: {}
        f:resources: {}
        f:targetRestrictions: {}
        f:targets: {}
    manager: fleet
    operation: Update
    time: "2021-01-22T13:56:00Z"
  - apiVersion: fleet.cattle.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:conditions: {}
        f:display:
          .: {}
          f:readyClusters: {}
        f:maxUnavailable: {}
        f:maxUnavailablePartitions: {}
        f:observedGeneration: {}
        f:summary:
          .: {}
          f:desiredReady: {}
          f:ready: {}
        f:unavailable: {}
        f:unavailablePartitions: {}
    manager: fleetcontroller
    operation: Update
    time: "2021-01-22T13:56:01Z"
  name: test123-multi-cluster-kustomize
  namespace: fleet-default
  resourceVersion: "128834872"
  selfLink: /apis/fleet.cattle.io/v1alpha1/namespaces/fleet-default/bundles/test123-multi-cluster-kustomize
  uid: 777465f5-f2f0-4e02-a6d9-d917bc90a8f7
spec:
  namespace: fleet-mc-kustomize-example
  resources:
  - content: |
      # Multi-Cluster Kustomize Example

      This example will deploy the [Kubernetes sample guestbook](https://github.com/kubernetes/examples/tree/master/guestbook/) application
      using kustomize. The app will be deployed into the `fleet-mc-kustomize-example` namespace.

      The application will be customized as follows per environment:

      * Dev clusters: Only the redis leader is deployed and not the followers.
      * Test clusters: Scale the front deployment to 3
      * Prod clusters: Scale the front deployment to 3 and set the service type to LoadBalancer

      ```yaml
      kind: GitRepo
      apiVersion: fleet.cattle.io/v1alpha1
      metadata:
        name: kustomize
        namespace: fleet-local
      spec:
        repo: https://github.com/rancher/fleet-examples
        paths:
        - multi-cluster/kustomize
        targets:
        - name: dev
          clusterSelector:
            matchLabels:
              env: dev

        - name: test
          clusterSelector:
            matchLabels:
              env: test

        - name: prod
          clusterSelector:
            matchLabels:
              env: prod
      ```
    name: README.md
  - content: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: frontend
      spec:
        selector:
          matchLabels:
            app: guestbook
            tier: frontend
        replicas: 1
        template:
          metadata:
            labels:
              app: guestbook
              tier: frontend
          spec:
            containers:
            - name: php-redis
              image: gcr.io/google-samples/gb-frontend:v4
              resources:
                requests:
                  cpu: 100m
                  memory: 100Mi
              ports:
              - containerPort: 80
    name: base/frontend-deployment.yaml
  - content: |
      apiVersion: v1
      kind: Service
      metadata:
        name: frontend
        labels:
          app: guestbook
          tier: frontend
      spec:
        type: NodePort
        ports:
        - port: 80
        selector:
          app: guestbook
          tier: frontend
    name: base/frontend-service.yaml
  - content: |
      resources:
      - frontend-deployment.yaml
      - frontend-service.yaml
      - redis-master-deployment.yaml
      - redis-master-service.yaml
      - redis-slave-deployment.yaml
      - redis-slave-service.yaml
    name: base/kustomization.yaml
  - content: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: redis-master
      spec:
        selector:
          matchLabels:
            app: redis
            role: master
            tier: backend
        replicas: 1
        template:
          metadata:
            labels:
              app: redis
              role: master
              tier: backend
          spec:
            containers:
            - name: master
              image: redis
              resources:
                requests:
                  cpu: 100m
                  memory: 100Mi
              ports:
              - containerPort: 6379
    name: base/redis-master-deployment.yaml
  - content: |
      apiVersion: v1
      kind: Service
      metadata:
        name: redis-master
        labels:
          app: redis
          role: master
          tier: backend
      spec:
        ports:
        - port: 6379
          targetPort: 6379
        selector:
          app: redis
          role: master
          tier: backend
    name: base/redis-master-service.yaml
  - content: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: redis-slave
      spec:
        selector:
          matchLabels:
            app: redis
            role: slave
            tier: backend
        replicas: 2
        template:
          metadata:
            labels:
              app: redis
              role: slave
              tier: backend
          spec:
            containers:
            - name: slave
              image: gcr.io/google_samples/gb-redisslave:v1
              resources:
                requests:
                  cpu: 100m
                  memory: 100Mi
              ports:
              - containerPort: 6379
    name: base/redis-slave-deployment.yaml
  - content: |
      apiVersion: v1
      kind: Service
      metadata:
        name: redis-slave
        labels:
          app: redis
          role: slave
          tier: backend
      spec:
        ports:
        - port: 6379
        selector:
          app: redis
          role: slave
          tier: backend
    name: base/redis-slave-service.yaml
  - content: |
      namespace: fleet-mc-kustomize-example
      targetCustomizations:
      - name: dev
        clusterSelector:
          matchLabels:
            env: dev
        kustomize:
          dir: overlays/dev

      - name: test
        clusterSelector:
          matchLabels:
            env: test
        kustomize:
          dir: overlays/test

      - name: prod
        clusterSelector:
          matchLabels:
            env: prod
        kustomize:
          dir: overlays/prod
    name: fleet.yaml
  - content: |
      resources:
      - ../../base
      patches:
      - redis-slave-deployment.yaml
      - redis-slave-service.yaml
    name: overlays/dev/kustomization.yaml
  - content: |
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: redis-slave
      spec:
        replicas: 0
    name: overlays/dev/redis-slave-deployment.yaml
  - content: |
      kind: Service
      apiVersion: v1
      metadata:
        name: redis-slave
      spec:
        selector:
          role: master
    name: overlays/dev/redis-slave-service.yaml
  - content: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: frontend
      spec:
        replicas: 3
    name: overlays/prod/frontend-deployment.yaml
  - content: |
      kind: Service
      apiVersion: v1
      metadata:
        name: frontend
      spec:
        type: LoadBalancer
    name: overlays/prod/frontend-service.yaml
  - content: |
      resources:
      - ../../base
      patches:
      - frontend-deployment.yaml
      - frontend-service.yaml
    name: overlays/prod/kustomization.yaml
  - content: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: frontend
      spec:
        replicas: 3
    name: overlays/test/frontend-deployment.yaml
  - content: |
      resources:
      - ../../base
      patches:
      - frontend-deployment.yaml
    name: overlays/test/kustomization.yaml
  targetRestrictions:
  - clusterSelector: {}
  targets:
  - clusterSelector:
      matchLabels:
        env: dev
    kustomize:
      dir: overlays/dev
    name: dev
  - clusterSelector:
      matchLabels:
        env: test
    kustomize:
      dir: overlays/test
    name: test
  - clusterSelector:
      matchLabels:
        env: prod
    kustomize:
      dir: overlays/prod
    name: prod
  - clusterSelector: {}
status:
  conditions:
  - lastUpdateTime: "2021-01-22T13:56:01Z"
    message: 'error while running post render on files: Object ''Kind'' is missing
      in ''{"resources":["frontend-deployment.yaml","frontend-service.yaml","redis-master-deployment.yaml","redis-master-service.yaml","redis-slave-deployment.yaml","redis-slave-service.yaml"]}'''
    reason: Error
    status: "False"
    type: Processed
  display:
    readyClusters: 0/0
  maxUnavailable: 0
  maxUnavailablePartitions: 0
  observedGeneration: 0
  summary:
    desiredReady: 0
    ready: 0
  unavailable: 0
  unavailablePartitions: 0
```

gz#14552
gz#14575

**Comment by ron1** [comment] 2021-01-22 15:07
@ janeczku See https://github.com/rancher/fleet-examples/pull/4 for a fix to this problem. BTW, I have been waiting quite a while for this reviewed PR to be committed.

**Comment by janeczku** [comment] 2021-01-22 15:19
@ron1  This is not caused by configuring an incorrect namespace in the GitRepo resource. I updated the reproduce steps to make clear what GitRepo configuration is used.

**Comment by ron1** [comment] 2021-01-22 15:40
@janeczku Thanks for the clarification. What version of Rancher and Fleet was used here?

**Comment by janeczku** [comment] 2021-01-22 15:45
Rancher v2.5.5 and the packaged Fleet Controller

**Comment by carneiroskeeled** [comment] 2021-01-26 18:14
Hey @StrongMonkey, I am having exactly the same issue that @janeczku described.

I was trying to create a similar repo structure show in https://github.com/rancher/fleet-examples/tree/master/multi-cluster/kustomize but nothing was loading. So I decided to try to run the example instead, setup a cluster with the label `env: dev` and apply the multi-cluster GitRepo example. 
I am also running `Rancher v2.5.5` and `rancher/fleet-agent:v0.3.3`.

It appears to be something with the `fleet.yaml` file or cluster label matching.

Can I help you in any way to identify where the problem is @StrongMonkey?

**Comment by carneiroskeeled** [comment] 2021-01-26 18:27
It errors trying to load https://github.com/rancher/fleet-examples/blob/master/multi-cluster/kustomize/base/kustomization.yaml for some reason.
I made a small test of having kustomize with a single-cluster setup and it is loading the `kustomization.yaml` as it is supposed, not throwing that error about missing `Object 'Kind'`.

**Comment by ron1** [comment] 2021-01-27 00:59
It appears the Bundle references non-existent test and prod clusters. Issue https://github.com/rancher/fleet/issues/171 describes scenarios like this where missing targets cause unexpected error reporting. Could that be the case here?

**Comment by carneiroskeeled** [comment] 2021-01-27 10:32
> 
> 
> It appears the Bundle pasted above references non-existent test and prod targets in addition to the valid dev target. Issue #171 describes scenarios like this where missing targets cause unexpected error reporting. Could that be the case here?

I tried an example without those non-existent targets and it still errors 🤐

**Comment by ron1** [comment] 2021-02-01 14:09
@carneiroskeeled @janeczku Did you remove the test and prod targets from both the GitRepo and the fleet.yaml? Does your revised Bundle still target non-existent test and prod clusters like the one pasted example above?

**Comment by carneiroskeeled** [comment] 2021-02-01 16:45
Hey @ron1, yes I did try that. It still produced the same error.

**Comment by lperrin-obs** [comment] 2021-02-02 08:57
I also tried this example and faced the same error. I only kept one `clusterSelector` targetting a cluster with a label "env=dev"

**Comment by chrishatfield86** [comment] 2021-02-16 03:33
I'm seeing the same issue with my own multi-cluster kustomize repo

```error while running post render on files: Object ''Kind'' is missing```

 I'm able to render the files locally without any issues.

**Comment by slickwarren** [comment] 2021-02-22 21:43
the fix has been tested (PASSED) on v2.5-head (a85f4d1) .  Waiting for https://github.com/rancher/fleet/issues/290 to land in order to test master-head

**Closed** 2021-02-24 00:17 UTC
Labels: [zube]: QA Next up, internal

**Comment by sra** [comment] 2021-02-28 12:03
This happens with the helm version as well, and I'm not sure it is fixed by the patch:

```
helm:
  repo: https://charts.bitnami.com/bitnami
  chart: bitnami/external-dns
  version: 4.8.4
  releaseName: external-dns
  values:
    provider: aws
    policy: sync
    rbac:
      create: true
    txtOwnerId: xxx
    domainFilters:
    - some.domain
 ```
I just updated the bundle image in a 2.5.5 rancher install to v0.3.4-rc7 and it fails with the same "error while running post render on files: Object 'Kind' is missing in ...." error.

**Comment by ron1** [comment] 2021-02-28 12:34
@sra It appears the particular chart you referenced  contains crds. So it must be handled specially, typically by putting crds in their own bundle. Although the error message is similar, what you are seeing with the chart you referenced is expected behavior and a much different issue than the one reported here.
