### ISSUE TITLE
How to increase bundles deployment concurrency of fleet agent

### ISSUE THREAD

**Issue by Mohamed-Adil-Ibrahim** [rancher/fleet#2252] opened 2024-03-21 13:56 UTC
- We have 59 uSerivces/Bundles that depends on each others without a pre-defined order at the moment, and in order for the application to be up and running we need to deploy them all together and let fleet to reconcile them - This is how we manage to deploy it using other GitOps tool but we are migrating to fleet-. 
- All of the bundles goes to "Wait Applied" state however in reality fleet agent only takes the first 5 bundles that is defined alphabetically in the GitRepo path, and some of them will go to "ContainerCreating" state since they waiting for other bundles to be deployed, but fleet doesn't continue deploying the rest of the bundles and all the bundles will stuck in "Wait Applied" state.

- My question is: How to let fleet to deploy all the bundles configured together ?

- The log from the fleet-agent looks like the following - omitting the bundle names -:
level=info msg="Deploying bundle ....." 
level=info msg="Deploying bundle ....."
beginning wait for 11 resources with timeout of 20m0s
level=info msg="Deploying bundle ....." 
beginning wait for 13 resources with timeout of 20m0s
level=info msg="Deploying bundle ....."
beginning wait for 12 resources with timeout of 20m0s
level=info msg="Deploying bundle ....."
beginning wait for 11 resources with timeout of 20m0s
beginning wait for 12 resources with timeout of 20m0s

**Comment by manno** [comment] 2024-04-10 13:34
Which version of fleet are you using?

**Comment by Mohamed-Adil-Ibrahim** [comment] 2024-04-10 13:58
Thanks for the reply, below are the versions I'm currently using:
Rancher:  v2.8.1
Dashboard: v2.8.0
Helm: v2.16.8-rancher2
Machine: v0.15.0-rancher106

Fleet Image: rancher/fleet:v0.9.1 
as well as I tried rancher/fleet:v0.8.0-debug-1842-4

**Comment by manno** [comment] 2024-06-26 08:10
Also related: https://github.com/rancher/fleet/issues/2552

**Comment by manno** [comment] 2024-10-23 13:52
Closing as a duplicate of https://github.com/rancher/fleet/issues/2915

**Closed by manno** 2024-10-23 13:52 UTC
Labels: kind/good-first-issue, area/performance, kind/bug, kind/question, area/config
