### ISSUE TITLE
CPU growth and error syncing errors in fleet-controller pod

### ISSUE THREAD

**Issue by dnoland1** [rancher/fleet#244] opened 2021-01-25 18:53 UTC
Over the last few days, seeing a constant growth in CPU and load on a k3s cluster:
![image](https://user-images.githubusercontent.com/468462/105751145-77d1b880-5efa-11eb-97e7-4d275995eb88.png)

According to top running on the VM, most of the CPU was being used by k3s-server and contained:
```
top - 03:09:04 up 13 days,  2:42,  0 users,  load average: 4.32, 3.48, 3.29
Tasks: 158 total,   1 running, 157 sleeping,   0 stopped,   0 zombie
%Cpu(s): 70.0 us, 24.7 sy,  0.0 ni,  1.0 id,  0.0 wa,  0.0 hi,  4.3 si,  0.0 st
MiB Mem :   7710.5 total,    142.8 free,   2935.5 used,   4632.2 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.   5451.0 avail Mem    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
3883618 root      20   0 1734520   1.5g  86644 S  93.4  20.1  10:13.69 k3s-ser+
3883633 root      20   0  292652 177016  67404 S  93.4   2.2   7:14.48 contain+
    342 systemd+  20   0   24356  12272   8028 S   5.3   0.2 461:44.41 systemd+
```
However, `kubectl pods top -A` was showing fleet-controller as the using the most CPU cores. Moved this pod from one node to the other at 10:35 (cordon problem node, deleted pod, let it respawn, uncordon node). Saw an immediate drop in the CPU:
![image](https://user-images.githubusercontent.com/468462/105751538-00505900-5efb-11eb-9dcc-a22be03c11ee.png)

Captured the fleet-controller pod the day before it was restarted. Seeing over 20K sync errors:
```
$ grep "error syncing" fleet-system-fleet-controller-56b7988677-zpzlc | wc -l
  22209
```
Last 5 lines of log:
```
$ tail -5 fleet-system-fleet-controller-56b7988677-zpzlc
time="2021-01-25T03:29:08Z" level=error msg="error syncing 'fleet-default/example3-multi-cluster-kustomize': handler bundle: error while running post render on files: Object 'Kind' is missing in '{\"resources\":[\"frontend-deployment.yaml\",\"frontend-service.yaml\",\"redis-master-deployment.yaml\",\"redis-master-service.yaml\",\"redis-slave-deployment.yaml\",\"redis-slave-service.yaml\"]}', requeuing"
time="2021-01-25T03:29:13Z" level=error msg="error syncing 'fleet-default/fleet-examples-multi-cluster-kustomize': handler bundle: error while running post render on files: Object 'Kind' is missing in '{\"resources\":[\"frontend-deployment.yaml\",\"frontend-service.yaml\",\"redis-master-deployment.yaml\",\"redis-master-service.yaml\",\"redis-slave-deployment.yaml\",\"redis-slave-service.yaml\"]}', requeuing"
time="2021-01-25T03:29:17Z" level=error msg="error syncing 'fleet-default/example2-multi-cluster-kustomize': handler bundle: error while running post render on files: Object 'Kind' is missing in '{\"resources\":[\"frontend-deployment.yaml\",\"frontend-service.yaml\",\"redis-master-deployment.yaml\",\"redis-master-service.yaml\",\"redis-slave-deployment.yaml\",\"redis-slave-service.yaml\"]}', requeuing"
time="2021-01-25T03:29:34Z" level=error msg="error syncing 'fleet-default/example-no-filter-multi-cluster-kustomize': handler bundle: error while running post render on files: Object 'Kind' is missing in '{\"resources\":[\"frontend-deployment.yaml\",\"frontend-service.yaml\",\"redis-master-deployment.yaml\",\"redis-master-service.yaml\",\"redis-slave-deployment.yaml\",\"redis-slave-service.yaml\"]}', requeuing"
time="2021-01-25T03:29:38Z" level=error msg="error syncing 'fleet-default/example-all-clusters-multi-cluster-kustomize': handler bundle: error while running post render on files: Object 'Kind' is missing in '{\"resources\":[\"frontend-deployment.yaml\",\"frontend-service.yaml\",\"redis-master-deployment.yaml\",\"redis-master-service.yaml\",\"redis-slave-deployment.yaml\",\"redis-slave-service.yaml\"]}', requeuing"
```
Appears fleet-controller has a "CPU leak" over time.

gz#14575

**Comment by StrongMonkey** [comment] 2021-02-05 22:18
Duplicate of https://github.com/rancher/fleet/issues/236. The bundle was in error state so fleet is trying to reconcile it.

**Comment by deniseschannon** [comment] 2021-02-05 22:18
Closing in favor of #236

**Closed by deniseschannon** 2021-02-05 22:18 UTC
Labels: internal
