### ISSUE TITLE
fleet does not work on kind cluster

### ISSUE THREAD

**Issue by gyliu513** [rancher/fleet#30] opened 2020-04-14 09:39 UTC
I created a kind cluster and want to use it as manager cluster, and when generate token on manager cluster, it failed as follows:

```console
root@gyliu-c11:~/fleet# fleet install agent-token > token
Error: invalid host 127.0.0.1, use --server-url to set a proper server URL
Usage:
  flt install agent-token [flags]

Flags:
  -c, --ca-file string            File containing optional CA cert for fleet management server
  -g, --group string              Cluster group to generate config for (default "default")
  -h, --help                      help for agent-token
      --no-ca
      --server-url string         The full URL to the fleet management server
      --system-namespace string   System namespace of the manager (default "fleet-system")
  -t, --ttl string                How long the generated registration token is valid, 0 means forever (default "1440m")

Global Flags:
  -k, --kubeconfig string   kubeconfig for authentication
  -n, --namespace string    namespace (default "default")

FATA[0001] invalid host 127.0.0.1, use --server-url to set a proper server URL
```

**Comment by gyliu513** [comment] 2020-04-14 09:46
It works after I added `server-url` as follows:

```
root@gyliu-c11:~/fleet# fleet install agent-token --server-url=https://172.16.250.138:8001 > token
```

But after the token was generated, then I run `kubectl apply -f token` it failed as follows:

```console
root@gyliu-c21:~/fleet# kubectl apply -f token  --v=8
I0414 02:45:10.851055   30906 loader.go:357] Config loaded from file /root/.kube/config
I0414 02:45:10.852583   30906 round_trippers.go:383] GET https://127.0.0.1:32768/openapi/v2
I0414 02:45:10.852625   30906 round_trippers.go:390] Request Headers:
I0414 02:45:10.852635   30906 round_trippers.go:393]     Accept: application/com.github.proto-openapi.spec.v2@v1.0+protobuf
I0414 02:45:10.852646   30906 round_trippers.go:393]     User-Agent: kubectl/v1.10.4 (linux/amd64) kubernetes/5ca598b
I0414 02:45:10.868411   30906 round_trippers.go:408] Response Status: 200 OK in 15 milliseconds
I0414 02:45:10.868441   30906 round_trippers.go:411] Response Headers:
I0414 02:45:10.868446   30906 round_trippers.go:414]     Last-Modified: Tue, 14 Apr 2020 09:35:58 GMT
I0414 02:45:10.868453   30906 round_trippers.go:414]     Vary: Accept-Encoding
I0414 02:45:10.868462   30906 round_trippers.go:414]     Vary: Accept
I0414 02:45:10.868467   30906 round_trippers.go:414]     X-From-Cache: 1
I0414 02:45:10.868478   30906 round_trippers.go:414]     X-Varied-Accept: application/com.github.proto-openapi.spec.v2@v1.0+protobuf
I0414 02:45:10.868485   30906 round_trippers.go:414]     Content-Type: application/octet-stream
I0414 02:45:10.868495   30906 round_trippers.go:414]     Etag: "D8E570192E40549B09AD30E3D3D9E0A03CAB17424C5A10BEFBD6141937132A6CD598A0B8D1017AB10A86965673AF6C938C739886029BE546CB81009A66718600"
I0414 02:45:10.868502   30906 round_trippers.go:414]     Date: Tue, 14 Apr 2020 09:45:10 GMT
I0414 02:45:10.868522   30906 round_trippers.go:414]     Accept-Ranges: bytes
I0414 02:45:11.084715   30906 request.go:872] Response Body:
00000000  0a 03 32 2e 30 12 15 0a  0a 4b 75 62 65 72 6e 65  |..2.0....Kuberne|
00000010  74 65 73 12 07 76 31 2e  31 37 2e 30 42 e0 8a 88  |tes..v1.17.0B...|
00000020  01 12 b9 28 0a 36 2f 61  70 69 2f 76 31 2f 77 61  |...(.6/api/v1/wa|
00000030  74 63 68 2f 6e 61 6d 65  73 70 61 63 65 73 2f 7b  |tch/namespaces/{|
00000040  6e 61 6d 65 73 70 61 63  65 7d 2f 63 6f 6e 66 69  |namespace}/confi|
00000050  67 6d 61 70 73 2f 7b 6e  61 6d 65 7d 12 fe 27 12  |gmaps/{name}..'.|
00000060  dd 04 0a 07 63 6f 72 65  5f 76 31 1a b0 01 77 61  |....core_v1...wa|
00000070  74 63 68 20 63 68 61 6e  67 65 73 20 74 6f 20 61  |tch changes to a|
00000080  6e 20 6f 62 6a 65 63 74  20 6f 66 20 6b 69 6e 64  |n object of kind|
00000090  20 43 6f 6e 66 69 67 4d  61 70 2e 20 64 65 70 72  | ConfigMap. depr|
000000a0  65 63 61 74 65 64 3a 20  75 73 65 20 74 68 65 20  |ecated: use the |
000000b0  27 77 61 74 63 68 27 20  70 61 72 61 6d 65 74 65  |'watch' paramete|
000000c0  72 20 77 69 74 68 20 61  20 6c 69 73 74 20 6f 70  |r with a list o [truncated 14227576 chars]
F0414 02:45:11.142457   30906 helpers.go:119] error: SchemaError(io.k8s.api.apps.v1.DeploymentCondition): invalid object doesn't have additional properties
```

**Comment by BenHimsel** [comment] 2020-04-20 17:40
I think the url needs to be something resolvable from the agent's perspective. So 127.0.0.1 would be the agent attempting to communicate with itself. You likely need to use the fully qualified name of the host that the management cluster is running on and you will also likely need to put that FQDN of the host into Subject Alternate Name on the certificate on the API.

The url can be set with the `fleet install agent-token --server-url`.

This is also a duplicate of issue #33 just not k3s specific.

**Comment by gyliu513** [comment] 2020-04-21 09:17
Thanks @BenHimsel but from https://github.com/rancher/fleet/issues/30#issuecomment-613339507 , you can see I was actually generating the token via the command as you proposed, am I missing anything? Thanks.

```
root@gyliu-c11:~/fleet# fleet install agent-token --server-url=https://172.16.250.138:8001 > token
```

**Comment by angudadevops** [comment] 2020-05-18 22:44
Start k3s with bind address of your host ip like below, 
```
sudo k3s server --bind-address 10.110.16.101 --advertise-address 10.110.16.101
```
Then use your k3s API address as server-url like below 
```
fleet install agent-token --server-url=https://10.110.16.101:6443 --kubeconfig /etc/rancher/k3s/k3s.yaml > default-token
```
This works for me

**Closed** 2020-05-19 00:24 UTC

**Comment by tuananh** [comment] 2020-09-01 06:47
@gyliu513 how did you fix this issue with cluster created by kind?
