### ISSUE TITLE
Fleet is not cleaning up objects on cluster delete

### ISSUE THREAD

**Issue by dramich** [rancher/fleet#478] opened 2021-08-04 21:20 UTC
After a cluster is deleted multiple objects are left:
ClusterRegistration
Role
RoleBinding

These should be deleted when the cluster is deleted.

**Comment by thedadams** [comment] 2021-08-04 21:40
This seems to cause problems with the following scenario:
1. Create an RKE2 cluster.
2. Wait for the cluster to become active.
3. Delete the cluster.
4. Create a cluster with the same name as the first.
The cluster will get provisioned, but will not become active. There will be an Unauthorized error in the UI.

It seems that there is a role leftover from the first cluster with name `request-*****` that is not getting deleted. Deleting this role before recreating the cluster allowed it to come up as active.

**Comment by nickgerace** [comment] 2021-08-04 22:12
What is likely happening is that the `NoDeleteGVK` is including cluster namespaces. Since they have the same name, it is re-using data from the previous namespace.

We need to keep `fleet-system` alive for 2.5.x to 2.6.x upgrades, so the solution to this will likely involve only protecting GVR corresponding to `fleet-system`, and not protecting other namespaces from wrangler applies.

bootstrapping and pre-controller registration - https://github.com/rancher/fleet/pull/468 (https://github.com/rancher/fleet/blob/96c8c497e7a44e349200c08375203e3044e7df7b/pkg/controllers/controllers.go#L78)
import scenarios - https://github.com/rancher/fleet/pull/475

**Comment by nickgerace** [comment] 2021-08-04 22:25
Worked out a potential solution with @StrongMonkey. Co-assigning for the time being after offline discussion

**Comment by davidnuzik** [comment] 2021-08-10 21:34
**My checks Failed**
 
**Reproduction Steps:**

Not required.
 
**Validation Steps:**

Rancher version: v2.6.0-rc2 (8/10/21) (rc2 is `9f6398367`)
Rancher cluster type: single-node docker
Docker version: 19.03
 
Downstream cluster type: rke2
Downstream K8s version: v1.21.3-rc4+rke2r2
 
Validation steps:

1. Provision Rancher Server. Use kubectl to query the local cluster for all Pods, ClusterRegistration, Role, and RoleBinding. This is out "starting point"
2. Provision a downstream rke2 cluster. It should not matter, but in my case I created a 1-node cluster with the DigitalOcean node driver. Wait for the cluster to fully provision - give it a minute or two (just in case fleet is wrapping anything up).
3. Delete the cluster. Give this a minute or two to fully complete (just in case fleet is wrapping anything up).
4. Use kubectl to query the local cluster for all Pods, ClusterRegistration, Role, and RoleBinding. Diff against what we captured at first with our initial output of these.

Upon diffing, there are some unexpected objects that still remain:
ClusterRegistration still has an object for the cluster I created. I should not see the "dave-rke2-1node" object.
```
NAMESPACE       NAME            CLUSTER-NAME      LABELS
fleet-default   request-mslv2   dave-rke2-1node   
fleet-local     request-v7srt   local
```
Role has two new objects maybe one or both of these are expected. I am not sure so mentioning these two NEW objects:
```
NAMESPACE                      NAME                                                           CREATED AT
cattle-global-data             cc-d4hl5-cc-d4hl5-a                                            2021-08-10T21:06:53Z
t-default                  request-mslv2                                                  2021-08-10T21:11:53Z
```
RoleBinding has numerous objects remaining, perhaps some of these are expected:
```
NAMESPACE                                NAME                                                              ROLE                                                                AGE
cattle-global-data                       cc-d4hl5-cc-d4hl5-a                                               Role/cc-d4hl5-cc-d4hl5-a                                            12m
cattle-global-data                       u-333mdfbbrn-global-catalog-binding                               Role/global-catalog                                                 7m54s
cattle-global-data                       u-imhycortkw-global-catalog-binding                               Role/global-catalog                                                 7m54s
cattle-global-data                       u-p7ijtcpnwr-global-catalog-binding                               Role/global-catalog                                                 7m54s
fleet-default                            request-mslv2                                                     Role/request-mslv2                                                  7m30s
fleet-local                              r-cluster-local-view-u-pffk4ub6ie-member                          Role/r-cluster-local-view                                           7m56s
fleet-local                              r-cluster-local-view-u-quwgsmvf6f-member                          Role/r-cluster-local-view                                           7m56s
```

Additional Info:
fleet-agent pod logs:
```
I0810 20:54:33.614869       1 leaderelection.go:243] attempting to acquire leader lease cattle-fleet-system/fleet-agent-lock...
I0810 20:54:37.745180       1 leaderelection.go:253] successfully acquired lease cattle-fleet-system/fleet-agent-lock
time="2021-08-10T20:54:37Z" level=info msg="Starting /v1, Kind=ServiceAccount controller"
time="2021-08-10T20:54:37Z" level=info msg="Starting /v1, Kind=ConfigMap controller"
time="2021-08-10T20:54:37Z" level=info msg="Starting /v1, Kind=Secret controller"
time="2021-08-10T20:54:37Z" level=info msg="Starting /v1, Kind=Node controller"
time="2021-08-10T20:54:37Z" level=info msg="Starting fleet.cattle.io/v1alpha1, Kind=BundleDeployment controller"
time="2021-08-10T20:54:37Z" level=info msg="getting history for release fleet-agent-local"
time="2021-08-10T20:54:37Z" level=info msg="getting history for release fleet-agent-local"
time="2021-08-10T20:54:38Z" level=info msg="getting history for release fleet-agent-local"
time="2021-08-10T20:54:38Z" level=info msg="getting history for release fleet-agent-local"
time="2021-08-10T20:54:38Z" level=info msg="getting history for release fleet-agent-local"
time="2021-08-10T20:54:38Z" level=info msg="getting history for release fleet-agent-local"
time="2021-08-10T20:54:40Z" level=info msg="getting history for release fleet-agent-local"
time="2021-08-10T20:54:40Z" level=info msg="getting history for release fleet-agent-local"
time="2021-08-10T20:54:40Z" level=info msg="getting history for release fleet-agent-local"
time="2021-08-10T20:54:40Z" level=info msg="getting history for release fleet-agent-local"
time="2021-08-10T20:54:40Z" level=info msg="getting history for release fleet-agent-local"
time="2021-08-10T20:54:40Z" level=info msg="getting history for release fleet-agent-local"
time="2021-08-10T20:55:03Z" level=info msg="preparing upgrade for fleet-agent-local"
time="2021-08-10T20:55:03Z" level=info msg="performing update for fleet-agent-local"
time="2021-08-10T20:55:03Z" level=info msg="dry run for fleet-agent-local"
time="2021-08-10T20:55:03Z" level=info msg="Helm: Upgrading fleet-agent-local"
time="2021-08-10T20:55:03Z" level=info msg="preparing upgrade for fleet-agent-local"
time="2021-08-10T20:55:04Z" level=info msg="performing update for fleet-agent-local"
time="2021-08-10T20:55:04Z" level=info msg="creating upgraded release for fleet-agent-local"
time="2021-08-10T20:55:04Z" level=info msg="updating status for upgraded release for fleet-agent-local"
time="2021-08-10T20:55:04Z" level=info msg="getting history for release fleet-agent-local"
time="2021-08-10T20:55:04Z" level=info msg="getting history for release fleet-agent-local"
time="2021-08-10T20:55:04Z" level=info msg="preparing upgrade for fleet-agent-local"
time="2021-08-10T20:55:04Z" level=info msg="performing update for fleet-agent-local"
time="2021-08-10T20:55:04Z" level=info msg="dry run for fleet-agent-local"
time="2021-08-10T20:55:04Z" level=info msg="Helm: Upgrading fleet-agent-local"
time="2021-08-10T20:55:04Z" level=info msg="preparing upgrade for fleet-agent-local"
time="2021-08-10T20:55:05Z" level=info msg="performing update for fleet-agent-local"
time="2021-08-10T20:55:05Z" level=info msg="creating upgraded release for fleet-agent-local"
time="2021-08-10T20:55:05Z" level=info msg="updating status for upgraded release for fleet-agent-local"
time="2021-08-10T20:55:05Z" level=info msg="getting history for release fleet-agent-local"
time="2021-08-10T20:55:05Z" level=info msg="getting history for release fleet-agent-local"
time="2021-08-10T20:55:05Z" level=info msg="getting history for release fleet-agent-local"
time="2021-08-10T20:55:05Z" level=info msg="getting history for release fleet-agent-local"
time="2021-08-10T20:55:05Z" level=info msg="getting history for release fleet-agent-local"
time="2021-08-10T21:24:37Z" level=info msg="getting history for release fleet-agent-local"
time="2021-08-10T21:24:37Z" level=info msg="getting history for release fleet-agent-local"
time="2021-08-10T21:24:37Z" level=info msg="getting history for release fleet-agent-local"
```

fleet-controller pod logs:
```
time="2021-08-10T20:54:05Z" level=info msg="No access to list CRDs, assuming CRDs are pre-created."
I0810 20:54:05.959715       1 leaderelection.go:243] attempting to acquire leader lease cattle-fleet-system/fleet-controller-lock...
I0810 20:54:05.993652       1 leaderelection.go:253] successfully acquired lease cattle-fleet-system/fleet-controller-lock
E0810 20:54:06.032801       1 reflector.go:138] pkg/mod/github.com/rancher/client-go@v0.21.3-fleet1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.ImageScan: failed to list *v1alpha1.ImageScan: the server could not find the requested resource (get imagescans.meta.k8s.io)
E0810 20:54:06.038006       1 reflector.go:138] pkg/mod/github.com/rancher/client-go@v0.21.3-fleet1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.ClusterRegistration: failed to list *v1alpha1.ClusterRegistration: the server could not find the requested resource (get clusterregistrations.meta.k8s.io)
E0810 20:54:06.077584       1 reflector.go:138] pkg/mod/github.com/rancher/client-go@v0.21.3-fleet1/tools/cache/reflector.go:167: Failed to watch *v1.GitJob: failed to list *v1.GitJob: the server could not find the requested resource (get gitjobs.meta.k8s.io)
E0810 20:54:06.101624       1 reflector.go:138] pkg/mod/github.com/rancher/client-go@v0.21.3-fleet1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.BundleNamespaceMapping: failed to list *v1alpha1.BundleNamespaceMapping: the server could not find the requested resource (get bundlenamespacemappings.meta.k8s.io)
E0810 20:54:06.102285       1 reflector.go:138] pkg/mod/github.com/rancher/client-go@v0.21.3-fleet1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.BundleDeployment: failed to list *v1alpha1.BundleDeployment: the server could not find the requested resource (get bundledeployments.meta.k8s.io)
E0810 20:54:06.104441       1 reflector.go:138] pkg/mod/github.com/rancher/client-go@v0.21.3-fleet1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.ClusterGroup: failed to list *v1alpha1.ClusterGroup: the server could not find the requested resource (get clustergroups.meta.k8s.io)
E0810 20:54:06.106180       1 reflector.go:138] pkg/mod/github.com/rancher/client-go@v0.21.3-fleet1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.ClusterRegistrationToken: failed to list *v1alpha1.ClusterRegistrationToken: the server could not find the requested resource (get clusterregistrationtokens.meta.k8s.io)
E0810 20:54:06.110329       1 reflector.go:138] pkg/mod/github.com/rancher/client-go@v0.21.3-fleet1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.GitRepo: failed to list *v1alpha1.GitRepo: the server could not find the requested resource (get gitrepos.meta.k8s.io)
E0810 20:54:06.116863       1 reflector.go:138] pkg/mod/github.com/rancher/client-go@v0.21.3-fleet1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.GitRepoRestriction: failed to list *v1alpha1.GitRepoRestriction: the server could not find the requested resource (get gitreporestrictions.meta.k8s.io)
E0810 20:54:06.125340       1 reflector.go:138] pkg/mod/github.com/rancher/client-go@v0.21.3-fleet1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.Content: failed to list *v1alpha1.Content: the server could not find the requested resource (get contents.meta.k8s.io)
E0810 20:54:06.935906       1 reflector.go:138] pkg/mod/github.com/rancher/client-go@v0.21.3-fleet1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.GitRepoRestriction: failed to list *v1alpha1.GitRepoRestriction: the server could not find the requested resource (get gitreporestrictions.meta.k8s.io)
E0810 20:54:06.940713       1 reflector.go:138] pkg/mod/github.com/rancher/client-go@v0.21.3-fleet1/tools/cache/reflector.go:167: Failed to watch *v1.GitJob: failed to list *v1.GitJob: the server could not find the requested resource (get gitjobs.meta.k8s.io)
E0810 20:54:07.014374       1 reflector.go:138] pkg/mod/github.com/rancher/client-go@v0.21.3-fleet1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.ClusterGroup: failed to list *v1alpha1.ClusterGroup: the server could not find the requested resource (get clustergroups.meta.k8s.io)
E0810 20:54:07.044606       1 reflector.go:138] pkg/mod/github.com/rancher/client-go@v0.21.3-fleet1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.ClusterRegistration: failed to list *v1alpha1.ClusterRegistration: the server could not find the requested resource (get clusterregistrations.meta.k8s.io)
E0810 20:54:07.060702       1 reflector.go:138] pkg/mod/github.com/rancher/client-go@v0.21.3-fleet1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.ImageScan: failed to list *v1alpha1.ImageScan: the server could not find the requested resource (get imagescans.meta.k8s.io)
E0810 20:54:07.103460       1 reflector.go:138] pkg/mod/github.com/rancher/client-go@v0.21.3-fleet1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.GitRepo: failed to list *v1alpha1.GitRepo: the server could not find the requested resource (get gitrepos.meta.k8s.io)
E0810 20:54:07.256871       1 reflector.go:138] pkg/mod/github.com/rancher/client-go@v0.21.3-fleet1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.ClusterRegistrationToken: failed to list *v1alpha1.ClusterRegistrationToken: the server could not find the requested resource (get clusterregistrationtokens.meta.k8s.io)
E0810 20:54:07.319204       1 reflector.go:138] pkg/mod/github.com/rancher/client-go@v0.21.3-fleet1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.Content: failed to list *v1alpha1.Content: the server could not find the requested resource (get contents.meta.k8s.io)
E0810 20:54:07.428198       1 reflector.go:138] pkg/mod/github.com/rancher/client-go@v0.21.3-fleet1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.BundleDeployment: failed to list *v1alpha1.BundleDeployment: the server could not find the requested resource (get bundledeployments.meta.k8s.io)
E0810 20:54:07.506568       1 reflector.go:138] pkg/mod/github.com/rancher/client-go@v0.21.3-fleet1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.BundleNamespaceMapping: failed to list *v1alpha1.BundleNamespaceMapping: the server could not find the requested resource (get bundlenamespacemappings.meta.k8s.io)
E0810 20:54:09.033279       1 reflector.go:138] pkg/mod/github.com/rancher/client-go@v0.21.3-fleet1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.GitRepo: failed to list *v1alpha1.GitRepo: the server could not find the requested resource (get gitrepos.meta.k8s.io)
E0810 20:54:09.085405       1 reflector.go:138] pkg/mod/github.com/rancher/client-go@v0.21.3-fleet1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.BundleDeployment: failed to list *v1alpha1.BundleDeployment: the server could not find the requested resource (get bundledeployments.meta.k8s.io)
E0810 20:54:09.133159       1 reflector.go:138] pkg/mod/github.com/rancher/client-go@v0.21.3-fleet1/tools/cache/reflector.go:167: Failed to watch *v1.GitJob: failed to list *v1.GitJob: the server could not find the requested resource (get gitjobs.meta.k8s.io)
E0810 20:54:09.168572       1 reflector.go:138] pkg/mod/github.com/rancher/client-go@v0.21.3-fleet1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.ClusterRegistration: failed to list *v1alpha1.ClusterRegistration: the server could not find the requested resource (get clusterregistrations.meta.k8s.io)
E0810 20:54:09.399931       1 reflector.go:138] pkg/mod/github.com/rancher/client-go@v0.21.3-fleet1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.ImageScan: failed to list *v1alpha1.ImageScan: the server could not find the requested resource (get imagescans.meta.k8s.io)
E0810 20:54:09.415545       1 reflector.go:138] pkg/mod/github.com/rancher/client-go@v0.21.3-fleet1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.GitRepoRestriction: failed to list *v1alpha1.GitRepoRestriction: the server could not find the requested resource (get gitreporestrictions.meta.k8s.io)
E0810 20:54:09.478445       1 reflector.go:138] pkg/mod/github.com/rancher/client-go@v0.21.3-fleet1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.Content: failed to list *v1alpha1.Content: the server could not find the requested resource (get contents.meta.k8s.io)
E0810 20:54:09.685723       1 reflector.go:138] pkg/mod/github.com/rancher/client-go@v0.21.3-fleet1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.BundleNamespaceMapping: failed to list *v1alpha1.BundleNamespaceMapping: the server could not find the requested resource (get bundlenamespacemappings.meta.k8s.io)
E0810 20:54:10.062982       1 reflector.go:138] pkg/mod/github.com/rancher/client-go@v0.21.3-fleet1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.ClusterGroup: failed to list *v1alpha1.ClusterGroup: the server could not find the requested resource (get clustergroups.meta.k8s.io)
E0810 20:54:10.206017       1 reflector.go:138] pkg/mod/github.com/rancher/client-go@v0.21.3-fleet1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.ClusterRegistrationToken: failed to list *v1alpha1.ClusterRegistrationToken: the server could not find the requested resource (get clusterregistrationtokens.meta.k8s.io)
time="2021-08-10T20:54:15Z" level=info msg="All controllers have been started"
time="2021-08-10T20:54:15Z" level=info msg="Starting fleet.cattle.io/v1alpha1, Kind=Cluster controller"
time="2021-08-10T20:54:15Z" level=info msg="Starting /v1, Kind=ConfigMap controller"
time="2021-08-10T20:54:15Z" level=info msg="Starting fleet.cattle.io/v1alpha1, Kind=ClusterRegistration controller"
time="2021-08-10T20:54:15Z" level=info msg="Starting gitjob.cattle.io/v1, Kind=GitJob controller"
time="2021-08-10T20:54:15Z" level=info msg="Starting fleet.cattle.io/v1alpha1, Kind=GitRepoRestriction controller"
time="2021-08-10T20:54:15Z" level=info msg="Starting fleet.cattle.io/v1alpha1, Kind=ClusterGroup controller"
time="2021-08-10T20:54:15Z" level=info msg="Starting rbac.authorization.k8s.io/v1, Kind=RoleBinding controller"
time="2021-08-10T20:54:15Z" level=info msg="Starting rbac.authorization.k8s.io/v1, Kind=ClusterRoleBinding controller"
time="2021-08-10T20:54:15Z" level=info msg="Starting fleet.cattle.io/v1alpha1, Kind=GitRepo controller"
time="2021-08-10T20:54:15Z" level=info msg="Starting /v1, Kind=ServiceAccount controller"
time="2021-08-10T20:54:15Z" level=info msg="Starting fleet.cattle.io/v1alpha1, Kind=Content controller"
time="2021-08-10T20:54:15Z" level=info msg="Starting fleet.cattle.io/v1alpha1, Kind=BundleDeployment controller"
time="2021-08-10T20:54:15Z" level=info msg="Starting fleet.cattle.io/v1alpha1, Kind=ClusterRegistrationToken controller"
time="2021-08-10T20:54:15Z" level=info msg="Starting rbac.authorization.k8s.io/v1, Kind=Role controller"
time="2021-08-10T20:54:15Z" level=info msg="Starting fleet.cattle.io/v1alpha1, Kind=BundleNamespaceMapping controller"
time="2021-08-10T20:54:15Z" level=info msg="Starting /v1, Kind=Namespace controller"
time="2021-08-10T20:54:15Z" level=info msg="Starting fleet.cattle.io/v1alpha1, Kind=ImageScan controller"
time="2021-08-10T20:54:15Z" level=info msg="Starting fleet.cattle.io/v1alpha1, Kind=Bundle controller"
time="2021-08-10T20:54:15Z" level=info msg="Starting /v1, Kind=Secret controller"
time="2021-08-10T20:54:15Z" level=info msg="Starting rbac.authorization.k8s.io/v1, Kind=ClusterRole controller"
time="2021-08-10T20:54:16Z" level=info msg="Deployed new agent for cluster fleet-local/local"
time="2021-08-10T20:54:16Z" level=info msg="System namespace (cattle-fleet-system) does not equal default namespace (fleet-system), checking for leftover objects..."
time="2021-08-10T20:54:17Z" level=info msg="Deleted old agent for cluster (fleet-local/local) in namespace cattle-fleet-system"
time="2021-08-10T20:54:17Z" level=info msg="Deployed new agent for cluster fleet-local/local"
time="2021-08-10T20:54:17Z" level=info msg="System namespace (cattle-fleet-system) does not equal default namespace (fleet-system), checking for leftover objects..."
time="2021-08-10T20:54:29Z" level=info msg="Cluster registration fleet-local/request-v7srt, cluster fleet-local/local granted [false]"
time="2021-08-10T20:54:29Z" level=info msg="Cluster registration fleet-local/request-v7srt, cluster fleet-local/local granted [true]"
time="2021-08-10T20:54:29Z" level=info msg="Cluster registration fleet-local/request-v7srt, cluster fleet-local/local granted [true]"
time="2021-08-10T20:54:29Z" level=info msg="Cluster registration fleet-local/request-v7srt, cluster fleet-local/local granted [true]"
time="2021-08-10T21:09:06Z" level=info msg="Marking orphaned content[s-57d4e0643cb8a72187110d6f235c04618544e330237b72552b35f7a6303c8] for deletion"
time="2021-08-10T21:09:06Z" level=info msg="Marking orphaned content[s-4acc6784fc71186b6faad8918cea6980d4360ca2edba2c983c5f1b3ea47bc] for deletion"
time="2021-08-10T21:11:43Z" level=info msg="Deployed new agent for cluster fleet-default/dave-rke2-1node"
time="2021-08-10T21:11:43Z" level=info msg="System namespace (cattle-fleet-system) does not equal default namespace (fleet-system), checking for leftover objects..."
time="2021-08-10T21:11:44Z" level=info msg="Deleted old agent for cluster (fleet-default/dave-rke2-1node) in namespace cattle-fleet-system"
time="2021-08-10T21:11:45Z" level=info msg="Deployed new agent for cluster fleet-default/dave-rke2-1node"
time="2021-08-10T21:11:45Z" level=info msg="System namespace (cattle-fleet-system) does not equal default namespace (fleet-system), checking for leftover objects..."
time="2021-08-10T21:11:53Z" level=info msg="Cluster registration fleet-default/request-mslv2, cluster fleet-default/dave-rke2-1node granted [false]"
time="2021-08-10T21:11:53Z" level=info msg="Cluster registration fleet-default/request-mslv2, cluster fleet-default/dave-rke2-1node granted [true]"
time="2021-08-10T21:11:53Z" level=info msg="Cluster registration fleet-default/request-mslv2, cluster fleet-default/dave-rke2-1node granted [true]"
time="2021-08-10T21:12:05Z" level=info msg="rate limited bundle(map[objectset.rio.cattle.io/hash:182141f75eaf8d8b2471e079cfafade568ad9bfa]) 1.00800297s"
time="2021-08-10T21:16:27Z" level=error msg="error syncing 'fleet-default/import-token-dave-rke2-1node': handler cluster-group-token: failed to delete fleet-default/import-token-dave-rke2-1node-c4b6dea4-46c8-4da8-9d48-b531-7f9c8 rbac.authorization.k8s.io/v1, Kind=Role for cluster-group-token fleet-default/import-token-dave-rke2-1node: roles.rbac.authorization.k8s.io \"import-token-dave-rke2-1node-c4b6dea4-46c8-4da8-9d48-b531-7f9c8\" not found, requeuing"
time="2021-08-10T21:19:06Z" level=info msg="Marking orphaned content[s-4acc6784fc71186b6faad8918cea6980d4360ca2edba2c983c5f1b3ea47bc] for deletion"
time="2021-08-10T21:19:06Z" level=info msg="Marking orphaned content[s-57d4e0643cb8a72187110d6f235c04618544e330237b72552b35f7a6303c8] for deletion"
time="2021-08-10T21:24:06Z" level=info msg="Deleting orphaned content[s-4acc6784fc71186b6faad8918cea6980d4360ca2edba2c983c5f1b3ea47bc]"
time="2021-08-10T21:24:06Z" level=info msg="Deleting orphaned content[s-57d4e0643cb8a72187110d6f235c04618544e330237b72552b35f7a6303c8]"
```

gitjob pod logs:
```
time="2021-08-10T20:54:05Z" level=info msg="Starting controller"
W0810 20:54:05.582845       1 client_config.go:614] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2021-08-10T20:54:05Z" level=info msg="Setting up webhook listener"
I0810 20:54:05.585292       1 leaderelection.go:243] attempting to acquire leader lease cattle-fleet-system/gitjob...
I0810 20:54:05.640284       1 leaderelection.go:253] successfully acquired lease cattle-fleet-system/gitjob
E0810 20:54:05.696622       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v1.GitJob: failed to list *v1.GitJob: the server could not find the requested resource (get gitjobs.meta.k8s.io)
E0810 20:54:07.031753       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v1.GitJob: failed to list *v1.GitJob: the server could not find the requested resource (get gitjobs.meta.k8s.io)
E0810 20:54:09.733832       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v1.GitJob: failed to list *v1.GitJob: the server could not find the requested resource (get gitjobs.meta.k8s.io)
time="2021-08-10T20:54:13Z" level=info msg="Starting gitjob.cattle.io/v1, Kind=GitJob controller"
time="2021-08-10T20:54:13Z" level=info msg="Starting /v1, Kind=Secret controller"
time="2021-08-10T20:54:13Z" level=info msg="Starting /v1, Kind=Pod controller"
time="2021-08-10T20:54:13Z" level=info msg="Starting batch/v1, Kind=Job controller"
```

rancher server logs:
[logs.txt](https://github.com/rancher/fleet/files/6964643/logs.txt)

**Comment by nickgerace** [comment] 2021-08-11 00:14
Met with @thedadams @StrongMonkey and come the following conclusions:

- The resources specified _are_ being cleaned up. (@davidnuzik I do not think we need another issue yet though since this one is broad enough)
- There are likely _other_ resources causes the issue. We tried deleting the Fleet `Cluster` CR, and that did not fix the issue either.
- The artifacts having issues are likely token-related.
- Restarting Rancher now solves the issue.

**Comment by thedadams** [comment] 2021-08-12 16:18
This issue with the deleting a cluster and recreating one with the same name now seems to be unrelated to Fleet. There is another [issue](https://github.com/rancher/rancher/issues/33897) in To Test to address this problem.

**Comment by nickgerace** [comment] 2021-08-12 16:24
In reference to https://github.com/rancher/fleet/issues/478#issuecomment-897773028, we are moving this back to To Test.

**Comment by davidnuzik** [comment] 2021-08-12 20:45
Closing, the results in my last test ([comment here](https://github.com/rancher/fleet/issues/478#issuecomment-896330207)) are actually expected. See Donnie and Nick's comments above for context.

**Closed by davidnuzik** 2021-08-12 20:45 UTC
Labels: [zube]: To Test, area/fleet, status/release-blocker
