### ISSUE TITLE
Adding github repo - Request entity too large: limit is 3145728 

### ISSUE THREAD

**Issue by naisanzaa** [rancher/fleet#1650] opened 2023-07-14 01:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Unable to add a public github repository to Continuous Delivery.

Error: 
```
Time="2023-07-14T01:45:17Z" level=fatal msg="Request entity too large: limit is 3145728"

```

### Expected Behavior

Add github repo.

### Steps To Reproduce

1. go to Continuous Delivery
2. add github https link
3. error

### Environment

```markdown
Rancher	v2.7.5
Dashboard	v2.7.5
Helm	v2.16.8-rancher2
Machine	v0.15.0-rancher100
```

### Anything else?

related: https://github.com/rancher/fleet/issues/205

**Comment by kkaempf** [comment] 2023-07-14 07:18
Please add a link to the public github repo here so we can reproduce your problem.

**Comment by naisanzaa** [comment] 2023-07-14 09:19
> Please add a link to the public github repo here so we can reproduce your problem.

https://github.com/TheShellLand/automonisaur

**Comment by kkaempf** [comment] 2023-07-14 09:54
Thanks.

This repo has huge `docs` (1.8 MB) and a huge Python stack (`automon` 2.2 MB) - not really suitable for Fleet 🤔 

You probably want to move the files relevant for Fleet to a sub-directory.

**Comment by Martin-Weiss** [comment] 2023-08-01 16:52
I have the same issue after upgrade of rancher 2.6.8 to 2.7.5 and fleet just uninstalled the app from all downstream and from the local cluster! This is really critical...

There is not much / just yaml files in our git repo!

Any idea for a workaround and ETA for a fix?

**Comment by kkaempf** [comment] 2023-08-02 07:25
Hmm, it's probably not Git or Fleet but Kubernetes (resp. etcd).

Googling around reveals e.g.
https://stackoverflow.com/questions/60468110/kubernetes-object-size-limitations/60492986#60492986
And [this](https://github.com/helm/helm/issues/7264) from Helm 🤔

**Comment by Martin-Weiss** [comment] 2023-08-02 07:28
Hm - but why do we see this in Rancher 2.7.5 and did not see this in Rancher 2.6.8? What has been changed in fleet between these two versions that would bring us to this problem?

**Comment by kkaempf** [comment] 2023-08-02 07:37
I don't think Fleet's the culprit here 😉

**Comment by Martin-Weiss** [comment] 2023-08-02 07:40
Fleet does an uninstall after the upgrade of Rancher from 2.6.8 to 2.7.5. So something must have changed in fleet and maybe it is a design issue in fleet.. we really need to find a way to get more debug info.

**Comment by Martin-Weiss** [comment] 2023-08-02 08:33
In my case it really seems that the root cause of the problem is that targetCustomizations did not work for repo and version.. and now that works. In combination with the large rancher-monitoring helm chart (4MB extracted) this seems to cause some limits to be hit..

So this causes a problem (rancher-monitoring-crd chart - but same problem exists with rancher-monitoring chart even worse):

```
defaultNamespace: cattle-monitoring-system
helm:
  repo: https://registry-2.di.customer.de/chartrepo/prdr
  version: "100.1.3+up19.0.3"
  chart: rancher-monitoring-crd
  releaseName: rancher-monitoring-crd
  values:
targetCustomizations:
- name: sbxr
  helm:
    repo: https://registry-2.di.customer.de/chartrepo/sbxr
    version: "100.1.2+up19.0.3"
    values:
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: sbxr
- name: devr
  helm:
    repo: https://registry-2.di.customer.de/chartrepo/devr
    version: "100.1.2+up19.0.3"
    values:
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: devr
- name: tstr
  helm:
    repo: https://registry-2.di.customer.de/chartrepo/tstr
    version: "100.1.2+up19.0.3"
    values:
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: tstr
      stage: tstr
- name: prdr
  helm:
    repo: https://registry-2.di.customer.de/chartrepo/prdr
    version: "100.1.2+up19.0.3"
    values:
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: prdr
- name: local
  helm:
    repo: https://registry-2.di.customer.de/chartrepo/prdr
    version: "100.1.3+up19.0.3"
    values:
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: local

```

This does not cause a problem:

```
defaultNamespace: cattle-monitoring-system
helm:
  repo: https://registry-2.di.customer.de/chartrepo/prdr
  version: "100.1.3+up19.0.3"
  chart: rancher-monitoring-crd
  releaseName: rancher-monitoring-crd
  values:
targetCustomizations:
- name: sbxr
  helm:
    #repo: https://registry-2.di.customer.de/chartrepo/sbxr
    #version: "100.1.2+up19.0.3"
    values:
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: sbxr
- name: devr
  helm:
    #repo: https://registry-2.di.customer.de/chartrepo/devr
    #version: "100.1.2+up19.0.3"
    values:
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: devr
- name: tstr
  helm:
    #repo: https://registry-2.di.customer.de/chartrepo/tstr
    #version: "100.1.2+up19.0.3"
    values:
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: tstr
      stage: tstr
- name: prdr
  helm:
    #repo: https://registry-2.di.customer.de/chartrepo/prdr
    #version: "100.1.2+up19.0.3"
    values:
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: prdr
- name: local
  helm:
    #repo: https://registry-2.di.customer.de/chartrepo/prdr
    #version: "100.1.3+up19.0.3"
    values:
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: local

```

**Comment by raulcabello** [comment] 2023-08-03 10:13
> In my case it really seems that the root cause of the problem is that targetCustomizations did not work for repo and version.. and now that works. In combination with the large rancher-monitoring helm chart (4MB extracted) this seems to cause some limits to be hit..

That's correct. `targetCustomizations` for helm repo and versions was fixed in v0.6.0 [more info](https://github.com/rancher/fleet/pull/1011).  That means the `Bundle` now contains both versions of the chart. That Bundle is now too big to be stored in etcd, that's why you see the `Request entity too large: limit is 3145728` error.

> Fleet does an uninstall after the upgrade of Rancher from 2.6.8 to 2.7.5. So something must have changed in fleet and maybe it is a design issue in fleet.. we really need to find a way to get more debug info.

That looks like a separate issue. I found out some resources were redeployed when upgrading from 2.6.8 to 2.7.5. The problem with the monitoring chart is that old resources are removed, but the new `Bundle` can't be created because of the limit issue. I'm still investigating why resources are redeployed

**Comment by raulcabello** [comment] 2023-08-07 15:50
Resources are disappearing because a helm upgrade with empty resources is done. This is happening on Rancher upgrades for `Bundles` that contains a `repo` or `version` overridden in the helm options, which was fixed in fleet v0.6.0 [more info](https://github.com/rancher/fleet/pull/1011).

The problem is that the [checksum](https://github.com/rancher/fleet/blob/v0.7.0/pkg/bundlereader/resources.go#L199) is different as it is now using the right helm version from the `targetCustomization` override. This is causing that the fleet-agent doesn't find the `Chart.yaml` or any resources as the checksum is used for the files prefix, therefore it performs an upgrade with no resources. The `BundleDeployment` is modified when the fleet job modifies the `Bundle`, then the right checksum is used and resources are deployed successfully.

The problem with the `rancher-monitoring` chart is that it is too big to be stored in a `Bundle` when using multiple versions. Therefore, the upgrade with the empty resources is done, but the `Bundle` is not modified as the job fails

**Comment by manno** [comment] 2023-08-24 11:00
- [ ] Document etcd blob size depends on cluster
- [ ] Review existing size warning in docs
- [ ] Document multiple version via target customization increase bundle size

**Comment by weyfonk** [comment] 2023-08-30 13:04
Closing this (see previous comment for a rationale).

**Closed by weyfonk** 2023-08-30 13:04 UTC
Labels: [zube]: Working, kind/bug, area/fleet, team/fleet, JIRA

**Comment by jhoblitt** [comment] 2024-03-06 20:20
I ran into this problem as having two versions of the kube-prometheus-stack chart are now enough to trigger this.    It seems like this is likely to be a frequent issue and the only solution is to split the bundle into multiple objects, one resource per chart version.

**Comment by shkarface** [comment] 2024-03-28 07:32
I have the same issue while trying to install the groundcover chart. this is because Bundle contains non templated helm chart, so it's too big to store in etcd. is there any way to store only the templated resources instead of the whole chart (including comments, documentations and everything)

**Comment by strowi** [comment] 2024-07-04 08:59
Hi, it seems we just started seeing this problem with a bundle exceeding 3M with ~100 kustomize overlays. Is there any documentation/way we can test this (or a timeline for release)?
