### ISSUE TITLE
invalid_label_reference for magic labels

### ISSUE THREAD

**Issue by atsai1220** [rancher/fleet#689] opened 2021-12-21 22:38 UTC
We're seeing this error message in `fleet-controller` across multiple bundles after upgrading to Rancher v2.6.2.

This didn't use to happen and none of our objects have changed in Git.

```
level=error msg="error syncing 'fleet-local/velero-fleet-velero-config': handler bundle: invalid_label_reference global.fleet.clusterLabels.management.cattle.io/cluster-display-name in key clustername, requeuing"
```

Our `fleet.yaml`
``` yaml
helm:
  values:
    clustername: global.fleet.clusterLabels.management.cattle.io/cluster-display-name
```

**Comment by atsai1220** [comment] 2022-01-06 21:11
This seems pretty straight forward and I don't see anything wrong with this
https://github.com/rancher/fleet/blob/81d2950d2c614c609ece373e3a53db10ffe99a3a/pkg/target/target.go#L511-L545

**Comment by atsai1220** [comment] 2022-01-06 21:36
Turns out I just needed to delete my GitRepo object then re-create it. Not sure what kind of processes happens such that the fleet-controller could not see cluster labels during the `processLabelValues()` function.

**Comment by atsai1220** [comment] 2022-05-13 22:24
Still experiencing this intermittently even after removing the `GitRepo` object or redeploying `fleet-agent` on downstream clusters.

Rancher 2.6.3 - Rancher 2.6.5

**Comment by atsai1220** [comment] 2022-05-13 22:29
I can reproduce this now.

All clusters must have the label present or else the whole bundle fails with this error. So if any one cluster is missing this label then the whole bundle does not deploy.

**Comment by Shaked** [comment] 2022-08-29 11:33
Any plans to fix this? Maybe just set a `null` value for non existing labels or add a  `fleet.yaml` method to set a default in case value doesn't exist, something like: `label(global.fleet.clusterLabels.my_custom_label, true)`

**Comment by sowmyav27** [comment] 2022-12-29 21:20
Reopening for QA validaitons

**Comment by sowmyav27** [comment] 2022-12-29 22:08
@thardeck @olblak Can we please add a QA Test Template for this, looking for steps to reproduce the issue

**Comment by kkaempf** [comment] 2023-01-11 14:10
waiting for 0.5.2 release

**Comment by jameson-mcghee** [comment] 2023-01-18 20:25
When following the Testing steps outlined in the [Test Template](https://github.com/rancher/fleet/issues/689#issuecomment-1387112245), I was unable to reproduce the issue on `v2.6.5` or `v2.6.9` with _fleet_ versions `100.0.3+up0.3.9` (`v2.6.5`) and `100.1.1+up0.4.1` (`v2.6.9`).
cc @thardeck @anupama2501 

**Steps Attempted to Reproduce Issue:**
1. Provisioned a downstream cluster
2. Created a Git Repo with [Test Repo](https://github.com/rancher/fleet-examples) and _Path_: `multi-cluster/helm`
  - Added label while creating a Git Repo of `foo: bar` without adding a label on the downstream cluster that was provisioned
3. Went to `local` cluster `fleet-controller` logs
  - **Note:** I was unable to see any error logs

**Logs observed during testing on `v2.6.5`:**
[fleet-controller-784d6fbcd8-h96j5_fleet-controller.log](https://github.com/rancher/fleet/files/10450440/fleet-controller-784d6fbcd8-h96j5_fleet-controller.log)

**Logs observed during testing on `v2.6.9`:**
`time="2023-01-18T19:31:57Z" level=info msg="No access to list CRDs, assuming CRDs are pre-created."
I0118 19:31:57.277093 1 leaderelection.go:248] attempting to acquire leader lease cattle-fleet-system/fleet-controller-lock...`

**Comment by sowmyav27** [comment] 2023-01-19 00:37
@jameson-mcghee Can you please ensure the steps from test template are validated?

**Comment by jameson-mcghee** [comment] 2023-01-19 22:03
Additional testing has been done on `v2.6.2` in an attempt to reproduce this issue. As of this time, however, we have been unable to do so.  @thardeck, could you please provide some more context in the [Test Template](https://github.com/rancher/fleet/issues/689#issuecomment-1387112245) around what needs to be done to be able to observe/reproduce this issue?

**Additional Steps to Reproduce:**
1. Forked the [rancher/fleet-examples](https://github.com/rancher/fleet-examples) repo
2. Created a [branch on that fork](https://github.com/jameson-mcghee/fleet-examples/tree/test689)
3. Pulled it down locally, modified the `multi-cluster/helm/fleet.yaml` file, and pushed changes to the remote branch
 - Each of the following are `fleet.yaml` configurations that were used in an attempt to reproduce this issue:
   - [Attempt 1](https://github.com/rancher/fleet-examples/commit/e88087f210c0826d6543bff5bd81fda0972d0d54)
   - [Attempt 2](https://github.com/rancher/fleet-examples/commit/b9afaa432bd67a972a3fcbbc525d5492f57bc572)
   - [Attempt 3](https://github.com/rancher/fleet-examples/commit/5b1b64adc43332ce8e6c87e70b0b967268a0f7d7)
   - [Attempt 4](https://github.com/rancher/fleet-examples/commit/b5fe06011615ab211a2d5c2f459ac31d2384e4d7)
   - [Attempt 5](https://github.com/rancher/fleet-examples/commit/3593741b187e919f2d7a8c26edf7367ace90b19a)
   - [Attempt 6](https://github.com/rancher/fleet-examples/commit/3d07da7560560a8db7bf56924468f4520d0ac62b)
   - [Attempt 7](https://github.com/rancher/fleet-examples/commit/b7306ad2672a41e20887f11c80ebaeb558cf8564)
4. Opened the `fleet-controller` logs from the `local` branch
5. Created a `Git Repo` in `Continuous Delivery` pointing to the forked repo/branch with the path `multi-cluster/helm`
6. Observed both the Repo Detailed view as well as the `fleet-controller` logs, and no errors were observed

![image](https://user-images.githubusercontent.com/13294321/213571924-7213b202-99ae-4811-aa7e-e35ab7487c8d.png)

**Comment by sowmyav27** [comment] 2023-01-19 22:34
@jameson-mcghee I was able to reproduce the issue using this fleet.yaml mentioned in our docs [here](https://fleet.rancher.io/gitrepo-structure) - as [this](https://github.com/sowmyav27/fleet-examples/tree/master/multi-cluster/helm)

I see errors in fleet-controller 
```
time="2023-01-19T20:48:40Z" level=info msg="Cluster label 'global.fleet.clusterLabels.LABELNAME' for key 'variableName' is missing from some clusters, setting value to empty string for these clusters."
time="2023-01-19T20:48:54Z" level=info msg="Cluster label 'global.fleet.clusterLabels.LABELNAME' for key 'variableName' is missing from some clusters, setting value to empty string for these clusters."
```

**Comment by jameson-mcghee** [comment] 2023-01-20 19:20
We have now been able to reproduce the issue on Rancher version `v2.6.2` (_Fleet App_ version `100.0.1+up0.3.7`) as well as Rancher version `v2.7.0` by following the Steps to Reproduce below.  However, during testing on Rancher version `v2.7-head` (Commit ID: 6316baf) with _Fleet App_ version `101.1.0+up0.6.0-rc.1`, I was unable to reproduce the issue when following the steps to reproduce. I was able to see the message mentioned as part of the fix in the logs:
`time="2023-01-20T18:31:37Z" level=info msg="Cluster label 'global.fleet.clusterLabels.LABELNAME' for key 'variableName' is missing from some clusters, setting value to empty string for these clusters."`

**Steps to Reproduce:**
1. Forked the [rancher/fleet-examples](https://github.com/rancher/fleet-examples) repo
2. Created a [branch on that fork](https://github.com/jameson-mcghee/fleet-examples/tree/test689)
3. Pulled it down locally, modified the `multi-cluster/helm/fleet.yaml` file, and pushed changes to the remote branch
   - This is the `fleet.yaml` file that was able to reproduce the issue:
     - [fleet.yaml](https://github.com/jameson-mcghee/fleet-examples/blob/test689/multi-cluster/helm/fleet.yaml)
4. Opened the `fleet-controller` logs from the `local` branch
5. Created a _Git Repo_ in _Continuous Delivery_ pointing to the forked repo/branch with the _Path_ `multi-cluster/helm`
6. Observed the error in the `fleet-controller` logs

**`v2.6.2` Fleet Controller Logs:**
[fleet-controller-66cc4c6b5b-22282_fleet-controller.log](https://github.com/rancher/fleet/files/10467770/fleet-controller-66cc4c6b5b-22282_fleet-controller.log)

**`v2.7-head` (Commit ID: 6316baf) Fleet Controller Logs:**
[fleet-controller-7f4865bf5b-zccdm_fleet-controller.log](https://github.com/rancher/fleet/files/10469285/fleet-controller-7f4865bf5b-zccdm_fleet-controller.log)

**Additional Observations/Questions:**
@thardeck, I noticed in the logs that the new message is printed numerous times (see the `fleet-controller-7f4865bf5b-zccdm_fleet-controller.log`). Is this intended behavior? I thought that it would only print the statement once in the logs.

**Comment by olblak** [comment] 2023-01-31 17:58
The release candiate 0.5.2-rc2 is available https://github.com/rancher/charts/pull/2363

**Comment by jameson-mcghee** [comment] 2023-02-06 16:13
During testing on Rancher version `v2.7-head` (Commit ID: 9bb8d56) with _Fleet App_ version `101.1.0+up0.6.0-rc.2`, I was unable to reproduce the issue when following the steps to reproduce. I was able to see the message mentioned as part of the fix in the logs:
`time="2023-02-06T16:04:20Z" level=info msg="Cluster label 'global.fleet.clusterLabels.LABELNAME' for key 'variableName' is missing from some clusters, setting value to empty string for these clusters."`

Based on this, as well as previous testing, I am closing this ticket as Done.

**Steps to Reproduce:**
1. Fork the [rancher/fleet-examples](https://github.com/rancher/fleet-examples) repo
2. Created a [branch on that fork](https://github.com/jameson-mcghee/fleet-examples/tree/test689)
3. Pull it down locally, modify the `multi-cluster/helm/fleet.yaml` file, and push changes to the remote branch
   - This is the `fleet.yaml` file that was able to reproduce the issue:
     - [fleet.yaml](https://github.com/jameson-mcghee/fleet-examples/blob/test689/multi-cluster/helm/fleet.yaml)
4. Open the `fleet-controller` logs from the `local` branch
5. Provision a downstream RKE2 cluster
6. Create a _Git Repo_ in _Continuous Delivery_ pointing to the forked repo/branch with the _Path_ `multi-cluster/helm`
7. Observe the `fleet-controller` logs


**`v2.7-head` (Commit ID: 9bb8d56) Fleet Controller Logs:**
[fleet-controller-6fc98b8c85-dt6sm_fleet-controller.log](https://github.com/rancher/fleet/files/10664984/fleet-controller-6fc98b8c85-dt6sm_fleet-controller.log)

**Closed by jameson-mcghee** 2023-02-06 16:13 UTC
Labels: [zube]: QA Working, status/to-test, area/fleet, team/fleet
