### ISSUE TITLE
Cluster specific values

### ISSUE THREAD

**Issue by davidcorbin** [rancher/fleet#338] opened 2021-04-12 19:32 UTC
Is there a way to set cluster specific values in a helm chart deployment? Say you'd like to deploy a helm chart to 2 clusters, A and B but you'd like a value for a specific key in the values.yaml for A to be different from the value of the same key in cluster B. 

Any guidance is appreciated. Thanks!

**Comment by ron1** [comment] 2021-04-12 19:54
@davidcorbin Suggest you ask this type of question in the #fleet Rancher Slack Channel.

**Comment by dramich** [comment] 2021-04-12 20:07
closing as a duplicate of https://github.com/rancher/fleet/issues/152

**Closed by dramich** 2021-04-12 20:07 UTC
