### ISSUE TITLE
Fleet harcodes Capabilities.APIVersions to k8s v1.18.0

### ISSUE THREAD

**Issue by vCra** [rancher/fleet#513] opened 2021-08-31 10:14 UTC
When deploying a helm chart which specifies an APIVersion > 1.18, the templating of the chart fails with `chart requires kubeVersion: >=1.19.0-0 which is incompatible with Kubernetes v1.18.0`, even on k8s's versions > 1.18. This is currently [hardcoded at the controller level ](https://github.com/rancher/fleet/blob/cfbe1dce4e6a5d836ff949b2eee33dbde4da79ec/pkg/helmdeployer/template.go#L27). This should instead use the API version of the target cluster

### To Reproduce:

* Deploy a cluster > v1.18 (v1.20.9 RKE was used in my example)
* Create a gitrepo with a fleet.yaml which deploys a helmchart which specifies `kubeVersion > v1.18` - (the [v1 release of ingress-nginx](https://github.com/kubernetes/ingress-nginx/tree/helm-chart-4.0.1/charts/ingress-nginx) was my use case)
* The generated bundle gets stuck with `chart requires kubeVersion: >=1.19.0-0 which is incompatible with Kubernetes v1.18.0`

### Workarounds:

Remove `kubeVersion` from the charts `Chart.yaml` 

https://rancher-users.slack.com/archives/C013SSBKB6U/p1630336539011300

**Comment by StrongMonkey** [comment] 2021-12-07 19:21
Duplicate of https://github.com/rancher/fleet/issues/399. Closing

**Closed by StrongMonkey** 2021-12-07 19:21 UTC
Labels: internal, kind/bug, priority/high, loe/L, [zube]: Team Area 3, team/area3
