### ISSUE TITLE
Bundle State and Bundle Diff

### ISSUE THREAD

**Issue by manno** [rancher/fleet#1141] opened 2022-11-30 10:39 UTC
Resources created from controllers show up as orphaned and can't be ignored. Bundle diff don't work for deleted resources.

* SURE-2739
* SURE-2811
* SURE-3257
* SURE-4466
* SURE-4968
* rancher/fleet#313
* rancher/fleet#327
* rancher/fleet#461

Mentioned:
* https://github.com/rancher/fleet/issues/726
* https://github.com/rancher/fleet/issues/572

**Comment by raulcabello** [comment] 2022-12-07 16:35
There is a problem with new resources created by an operator if the operator copies the `objectset.rio.cattle.io/hash` label.
In this case wrangler plan thinks this new resource belongs to the bundle deployment which is not right. Therefore the resource is marked as `Orphaned` and status will never be `Ready`.

Example

Create a `GitRepo` with https://github.com/raulcabello/fleet-test/tree/main/ingress. It contains a `Certificate`, `Issuer` and an `Ingress`. `cert-manager` will create a new `Certificate` called `myingress-cert` for this ingress because it has this [annotation](https://github.com/raulcabello/fleet-test/blob/main/ingress/ingress.yaml#L6). `myingress-cert` does not belong to the helm release, however wrangler returns this certificate in the [plan.Delete](https://github.com/rancher/fleet/blob/master/modules/agent/pkg/deployer/manager.go#L106). This is happening because cert-manager [copies the labels](https://github.com/cert-manager/cert-manager/blob/master/pkg/controller/certificate-shim/sync.go#L360) from the `Ingress` into the new `Certificate`, therefore this new `Certificate` contains the label  `objectset.rio.cattle.io/hash`

**Comment by raulcabello** [comment] 2022-12-12 09:25
https://github.com/rancher/fleet/issues/327 is similar to the one I described above. In this case the `prometheus-operator` is creating 2 statefulsets that contains `objectset.rio.cattle.io/hash` label and `objectset.rio.cattle.io/id` annotation. The operator adds all the [labels and annotations](https://github.com/prometheus-operator/prometheus-operator/blob/19ca0371f3185e46c8f886e3ed43d7d8783d375b/pkg/alertmanager/statefulset.go#L94-L118) to the `Statefulsets` from the `AlertManager` resource which is created in the bundle deployment, therefore it contains the `objectset.rio.cattle.io/hash` label. Wrangler thinks this two resources were created by the bundle because they contain the `objectset.rio.cattle.io/hash` label.

**Comment by raulcabello** [comment] 2022-12-13 09:04
How does Wrangler apply work?

The `apply` client works similarly to applying yaml using kubectl. You can apply a state and the object will be created if it does not exist already or be updated to match the passed desired state if the object does exist already. 
If you just want to see which objects would be created, modified or deleted a `plan` can be created by calling `apply.dryRun()`. A `plan` contains three lists of resources for create, update and delete. An ID is used to identify all resources for a specific plan. This ID is stored in the `objectset.rio.cattle.io/id` annotation and in the `objectset.rio.cattle.io/hash` label.

How does monitor Bundle status work in Fleet?

-1) When a new `Bundle` is created the `objectset.rio.cattle.io/hash` label is added to all resources created in the helm [post render](https://github.com/rancher/fleet/blob/2f103190269a13d7333ebb5002e9bfbbac212fba/pkg/helmdeployer/deployer.go#L132-L143). The `BundleDeployment` name and some prefixes are used for the (SetID)[https://github.com/rancher/fleet/blob/2f103190269a13d7333ebb5002e9bfbbac212fba/modules/agent/pkg/deployer/monitor.go#L145], which will be the value of the `objectset.rio.cattle.io/hash label`
-2) Fleet agent uses wrangler [apply plan](https://github.com/rancher/fleet/blob/2f103190269a13d7333ebb5002e9bfbbac212fba/modules/agent/pkg/deployer/monitor.go#L36-L37) for monitoring status of the resources created by the bundle deployment. 

Problem

Wrangler apply uses the `objectset.rio.cattle.io/hash` label for finding all resources that are part of the same plan. This is a problem when some operators (such as `cert-manager` or `prometheus`) create dynamically resources and add this label to the new resources, then wrangler thinks this new resources are part of the plan. However they should not be part of the plan as they were not deployed by the bundle, that's why they are marked as `Orphaned`.

Possible solutions:

-1) Modify wrangler to track apply resources in a different way. Something like keeping track in `Secrets` instead of using the `objectset.rio.cattle.io/hash` label. The problem with this approach is that apply is used in many places in Rancher and keeping backwards compatibility it's not straightforward as when you upgrade existing Bundle deployments would have the label.

-2) Stop using wrangler apply for monitoring bundle status, use the information of the helm releases instead. We can fetch all resources that are part of the current release with helm manifest to see their status. Resources from old helm release versions would need to be compared to see if there are any orphan resources. I would go with this approach.

**Comment by manno** [comment] 2023-01-27 15:18
QA template in PR https://github.com/rancher/fleet/pull/1201#issuecomment-1387102755

**Comment by sowmyav27** [comment] 2023-02-07 03:38
@kkaempf @manno @olblak Can we add more info on how to reproduce the issue in the `Testing` section in QA Template? https://github.com/rancher/fleet/pull/1201#issuecomment-1387102755 ?

**Comment by raulcabello** [comment] 2023-02-08 08:56
@sowmyav27 I added more info on how to reproduce the issue [here](https://github.com/rancher/fleet/pull/1201#issuecomment-1387102755)

**Closed** 2023-02-08 16:11 UTC
Labels: [zube]: To Test, area/fleet, team/fleet, fleet/epic, area/bundle, JIRA
